import {demoMonthlySources} from '../analyticsDemo';
import {useQuery} from '@tanstack/react-query';
import {api,monthName,number} from '../api';
type AI={providers:{label:string;value:number}[];sessions:number;evidence:{source:string;sessions:number;provider:string}[]};
type Report={ai:AI;sources:{channel:string;sessions:number}[];start:string;end:string;partial:boolean;thresholded:boolean;data_loss:boolean;updated_at:string;warning?:string};
const paid=new Set(['Paid Search','Paid Social','Paid Shopping','Paid Video','Display','Cross-network','Audio','Paid Other']);
const organic=new Set(['Organic Search','Organic Social','Organic Shopping','Organic Video']);
const labels:Record<string,string>={'Organic Search':'Organische Suche','Organic Social':'Organische soziale Medien','Organic Shopping':'Organisches Shopping','Organic Video':'Organische Videos','Paid Search':'Bezahlte Suche','Paid Social':'Bezahlte soziale Medien','Paid Shopping':'Bezahltes Shopping','Paid Video':'Bezahlte Videos','Paid Other':'Weitere bezahlte Zugriffe','Direct':'Direktzugriffe','Referral':'Verweisende Websites','Email':'E-Mail','Unassigned':'Nicht zugeordnet','(not set)':'Nicht zugeordnet','Cross-network':'Kanalübergreifende Werbung'};
export function AnalyticsMonthlySources({month,demo}:{month:string;demo:boolean}){
 const q=useQuery<Report>({queryKey:['analytics-monthly-sources',month,demo,'ai-v3'],queryFn:()=>demo?Promise.resolve(demoMonthlySources(month)):api<Report>(`/analytics/monthly-sources?month=${month}&refresh=true`),staleTime:3600000});

 const groups=[{name:'Organisch',value:0},{name:'Bezahlt',value:0},{name:'Direkt',value:0},{name:'E-Mail',value:0},{name:'Verweisende Websites',value:0},{name:'Weitere / nicht zugeordnet',value:0}];
 q.data?.sources.forEach(r=>{const i=organic.has(r.channel)?0:paid.has(r.channel)?1:r.channel==='Direct'?2:r.channel==='Email'?3:r.channel==='Referral'?4:5;groups[i].value+=r.sessions});
 return <section className="monthly-sources" aria-label="Zugriffsquellen im Monat"><h3>Woher kommen die Zugriffe? <span>{monthName(month)}</span></h3>{demo&&<p>Illustrative Beispieldaten – keine echten Kontozugriffe.</p>}{q.isPending?<p role="status">Zugriffsquellen werden geladen…</p>:q.isError?<div role="alert"><p>Zugriffsquellen konnten nicht geladen werden.</p><button className="button" onClick={()=>q.refetch()}>Erneut versuchen</button></div>:<>
 <p>Sitzungen der gesamten GA4-Property · {new Date(q.data.start+'T12:00').toLocaleDateString('de-CH')} bis {new Date(q.data.end+'T12:00').toLocaleDateString('de-CH')}{q.data.partial?' · laufender Monat bis zum Datenstand':''}</p>
 {q.data.warning&&<p role="alert">{q.data.warning}</p>}
 <div className="monthly-origin-layout"><div className="monthly-origin-channels"><h4>Zugriffsquellen</h4><p>Sitzungen nach Kanal</p>
 {q.data.sources.length?<><dl className="monthly-origin-bars">{groups.map(g=>{const total=groups.reduce((sum,x)=>sum+x.value,0);const percent=total?g.value/total*100:0;return <div key={g.name}><dt>{g.name}</dt><dd><strong>{number(g.value)}</strong><span>{number(percent)} %</span></dd><div className="origin-bar" aria-hidden="true"><i style={{width:`${percent}%`}}/></div></div>})}</dl><details><summary>Alle Quellen im Detail</summary><dl className="monthly-source-details">{q.data.sources.map(r=><div key={r.channel}><dt>{labels[r.channel]||r.channel}</dt><dd>{number(r.sessions)} Sitzungen</dd></div>)}</dl></details></>:<p>Keine Quellenwerte geliefert.</p>}
 </div><div className="monthly-origin-geo"><h4>Zugriffe aus KI-Diensten</h4><p>In GA4 erkennbare KI-Quellen · im ausgewählten Monat</p>
 <p className="ai-traffic-total"><strong>{number(q.data.ai.sessions)}</strong> Sitzungen</p>
 {q.data.ai.providers.length?<><dl className="monthly-origin-bars geo-bars">{q.data.ai.providers.map(r=><div key={r.label}><dt>{r.label}</dt><dd><strong>{number(r.value)}</strong><span>Sitzungen</span></dd><div className="origin-bar" aria-hidden="true"><i style={{width:`${q.data.ai.sessions?r.value/q.data.ai.sessions*100:0}%`}}/></div></div>)}</dl><details><summary>Erfasste KI-Quellen</summary><dl>{q.data.ai.evidence.map(r=><div key={r.source}><dt>{r.source}</dt><dd>{number(r.sessions)} Sitzungen</dd></div>)}</dl></details></>:<p>In diesem Monat wurden keine Sitzungen mit einer erkannten KI-Quelle geliefert. Das schliesst weitere KI-Zugriffe ohne erkennbare Herkunft nicht aus.</p>}
 <p className="geo-note">Erkannt werden eindeutige Quelldomains von ChatGPT, Perplexity, Gemini, Claude, Copilot, DeepSeek und Grok. Google-, Bing- und Direktzugriffe werden nicht pauschal als KI gewertet. Diese Sitzungen sind bereits in den Zugriffsquellen links enthalten und dürfen nicht zusätzlich addiert werden. Die Balken zeigen den Anteil an den erkannten KI-Sitzungen.</p></div></div>
 <details><summary>So liest du diese Herkunftszahlen</summary><p>Organisch umfasst unbezahlte Such-, Social-, Shopping- und Videozugriffe. Bezahlt folgt den GA4-Werbekanalgruppen. Direktzugriffe, E-Mail und Verweise bleiben separat. Die Prozentwerte zeigen den Anteil an den gelieferten Sitzungen. KI-Zugriffe werden anhand der GA4-Sitzungsquelle zugeordnet. Das misst erkennbare Website-Zugriffe, nicht Erwähnungen oder Sichtbarkeit in KI-Antworten.</p></details>
 {(q.data.thresholded||q.data.data_loss)&&<p>GA4 meldet Einschränkungen bei der Aufschlüsselung. Detailwerte können unvollständig sein.</p>}
 </>}</section>;
}
