import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api,number,monthName} from '../api';
type Row={dimensions:string[];values:Record<string,number>};
type Item={title:string;kind:string;url:string;path:string;current:Record<string,number|null>|null;previous:Record<string,number|null>|null;sources:Row[];visitors:Row[];events:Row[];thresholded:boolean};
type Report={campaigns:Item[];start:string;end:string;previous_start:string;previous_end:string;updated_at:string;warning?:string};
const metricNames:Record<string,string>={screenPageViews:'Seitenaufrufe',totalUsers:'Besucher',sessions:'Sitzungen',engagementPerUser:'Ø aktive Zeit / Besucher (Sek.)'};
const paid=new Set(['Paid Search','Paid Social','Paid Shopping','Paid Video','Display','Cross-network','Audio','Paid Other']);
const unpaid=new Set(['Organic Search','Organic Social','Organic Shopping','Organic Video','Direct','Referral','Email','SMS','Mobile Push Notifications']);
function sourceGroup(s:string){return paid.has(s)?'Bezahlt':unpaid.has(s)?'Unbezahlt':'Nicht zugeordnet'}
export function AnalyticsPages({month,demo}:{month:string;demo:boolean}){
 const [selection,setSelection]=useState('');
 const q=useQuery({queryKey:['analytics-pages',month],queryFn:()=>api<Report>(`/analytics/campaigns?month=${month}`),enabled:!demo,staleTime:3600000});
 if(demo)return <section className="panel"><h2>Kampagnen & Vorstellungsseiten</h2><p>Die Seitenauswertung ist in der öffentlichen Demo nicht verfügbar.</p></section>;
 if(q.isPending)return <section className="panel" role="status"><h2>Kampagnen & Vorstellungsseiten</h2><p>Seitenkennzahlen werden geladen…</p></section>;
 if(q.isError)return <section className="panel" role="alert"><p>Seitenkennzahlen konnten nicht geladen werden.</p><button className="button" onClick={()=>q.refetch()}>Erneut versuchen</button></section>;
 return <section className="analytics-pages"><div className="section-heading"><div><h2>Landingpages & Vorstellungsseiten</h2><p>{monthName(month)} · Zeitraum {q.data.start} bis {q.data.end}</p></div><label>Seite auswählen<select value={selection} onChange={e=>setSelection(e.target.value)}><option value="">Alle Seiten</option>{q.data.campaigns.map(c=><option key={c.path} value={c.path}>{c.kind==='profile'?'Vorstellungsseite: ':''}{c.title}</option>)}</select></label></div>
 <p>Die Monatsauswahl erfolgt oben im Performance-Vergleich. Gemessen werden Aufrufe dieser Seiten, nicht nur Einstiege. Besucher und Sitzungen mehrerer Seiten dürfen nicht addiert werden.</p>{q.data.warning&&<p role="alert">{q.data.warning}</p>}
 {['campaign','profile'].filter(kind=>q.data.campaigns.some(c=>c.kind===kind&&(!selection||selection===c.path))).map(kind=><section key={kind}><h2>{kind==='profile'?'Vorstellungsseiten':'Kampagnen'}</h2>{q.data.campaigns.filter(c=>c.kind===kind&&(!selection||selection===c.path)).map(c=><article className="analytics-page" key={c.path}><h3><a href={c.url} target="_blank" rel="noreferrer">{c.title}</a></h3><p className="analytics-path">{c.path}</p><dl className="analytics-page-kpis">{Object.entries(metricNames).map(([k,label])=><div key={k}><dt>{label}</dt><dd>{number(c.current?.[k])}</dd><small>Vorperiode: {number(c.previous?.[k])}</small></div>)}</dl>{!c.current&&<p>Für diese Seite liefert GA4 im gewählten Monat keine Werte.</p>}{c.thresholded&&<p>GA4 schränkt diese Auswertung durch Datenschutzschwellen ein.</p>}
 <details><summary>Zugriffsquellen, Besucher & Aktionen</summary><div className="analytics-breakdown"><div><h4>Zugriffsquellen</h4>{c.sources.length?<dl>{c.sources.map(r=><div key={r.dimensions[0]}><dt>{r.dimensions[0]} · {sourceGroup(r.dimensions[0])}</dt><dd>{number(r.values.sessions)} Sitzungen</dd></div>)}</dl>:<p>Keine Quellenwerte vorhanden.</p>}</div><div><h4>Neue / wiederkehrende Besucher</h4>{c.visitors.length?<dl>{c.visitors.map(r=><div key={r.dimensions[0]}><dt>{r.dimensions[0]==='new'?'Neu':r.dimensions[0]==='returning'?'Wiederkehrend':'Nicht zugeordnet'}</dt><dd>{number(r.values.totalUsers)}</dd></div>)}</dl>:<p>Keine Besucheraufteilung vorhanden.</p>}<p>GA4-Zuordnung; eine Person kann im Zeitraum in mehreren Gruppen vorkommen.</p></div><div><h4>Erfasste Aktionen</h4>{c.events.length?<dl>{c.events.map(r=><div key={r.dimensions[0]}><dt>{{file_download:'Downloads',video_start:'Videostarts',video_progress:'Video-Fortschrittsereignisse',video_complete:'Video abgeschlossen'}[r.dimensions[0]]||r.dimensions[0]}</dt><dd>{number(r.values.eventCount)}</dd></div>)}</dl>:<p>Keine Download- oder Videoereignisse geliefert. Das belegt weder null Nutzung noch eingerichtetes Tracking.</p>}</div></div></details></article>)}</section>)}
 <p>Business Continuity wurde mit derselben URL für DE und FR geliefert und wird einmal gezählt. Vergleich: {q.data.previous_start} bis {q.data.previous_end}.</p><details><summary>So liest du die Seitenkennzahlen</summary><p>Seitenaufrufe zählen auch wiederholte Aufrufe. Besucher sind von GA4 erkannte Nutzer im Zeitraum; Geräte und Einwilligungen beeinflussen die Erkennung. Sitzungen beschreiben Besuche, in denen diese Seite erfasst wurde.</p><p>Ø aktive Zeit / Besucher = erfasste aktive Interaktionszeit dieser Seite geteilt durch ihre Besucher. Das ist kein Mass für die gesamte Zeit zwischen Öffnen und Schliessen eines Tabs. Fehlende Werte bleiben «—».</p><p>Bezahlt/unbezahlt folgt den GA4-Standardkanalgruppen; unbekannte Zuordnungen bleiben separat. Downloads und Videos zählen ausschliesslich tatsächlich gelieferte Ereignisse.</p></details></section>;
}
