import {useState} from 'react';
import {ChannelIcon} from './ui';
import type {Channel,Recommendation} from '../types';
import {Play, Search} from 'lucide-react';
import {channelEntries,recommendationAreas} from '../recommendationContent';
export function ChannelRecommendations({channels,items,onSelect,initialChannels=[],onOpenArea}:{channels:Channel[];items:Recommendation[];onSelect:(r:Recommendation)=>void;initialChannels?:string[];onOpenArea?:(area:'search'|'videos')=>void}){
 const [filter,setFilter]=useState(initialChannels);
 const areas=[...channels,...recommendationAreas];
 return <section className="compact-recommendations"><div className="section-heading"><h2>Empfehlungen nach Kanal und Themenbereich</h2></div><p>Priorisierte Handlungshinweise und ergänzende, ausdrücklich gekennzeichnete Beispiele. Beispiele sind keine Analyse der aktuellen Performance.</p><div className="channel-selector" role="group" aria-label="Empfehlungen nach Bereich filtern"><button aria-pressed={!filter.length} onClick={()=>setFilter([])}>Alle Bereiche</button>{areas.map(c=><button key={c.id} aria-pressed={filter.includes(c.id)} onClick={()=>setFilter([c.id])}>{c.name}</button>)}</div>{areas.filter(c=>!filter.length||filter.includes(c.id)).map(c=>{const list=channelEntries(c.id,items);return <section className="compact-channel" key={c.id}><header><div className="channel-title">{c.id==='search'?<Search size={30}/>:c.id==='videos'?<Play size={30}/>:<ChannelIcon id={c.id} size={30}/>}<h3>{c.name}</h3></div><span>{list.length} nächste Schritte</span>{onOpenArea&&(c.id==='search'||c.id==='videos')&&<button className="text-button" onClick={()=>onOpenArea(c.id as 'search'|'videos')}>Bereich öffnen</button>}</header><div className="compact-rec-grid">{list.map(({recommendation:r,example},i)=><article key={i}><small>{example?'Beispiel · vor Umsetzung prüfen':'Aus Kennzahlen / Analyse'}</small><h4>{r.title}</h4><p>{r.action}</p><button onClick={()=>onSelect(r)}>{example?'Beispiel ansehen':'Einordnung ansehen'}</button></article>)}</div>{!list.length&&<p>Noch keine Empfehlungen für diesen Kanal.</p>}</section>})}</section>;
}
