import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { CalendarDays, Download, RefreshCw, MapPin } from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip } from 'recharts';
import { api, number } from '../api';
import { saveCSV } from '../csv';
import { asset } from '../staticDemo';
import { PeriodInfo } from './PeriodInfo';
import { EditorialQuote } from './EditorialQuote';
import { RecommendationTeaser } from './RecommendationTeaser';
import './events.css';

type Event = { id:string; title:string; description:string; date:string|null; time:string; location:string; topic:string; image_url:string|null; source:"Microsoft Forms"|"Zoom"; attendees:number|null; recording_views:number|null; recording_duration_seconds:number|null; data_note:string; responses:number|null; registrations:number|null; employees:number|null; partners:number|null; customers:number|null; capacity:number|null; includes_companions:boolean; duplicate_candidate:boolean; timeline:{date:string;registrations:number}[] };
type Snapshot = { observed_at:string; source:string; events:Event[] };
type Data = { snapshot:Snapshot|null; automatic_sync:boolean; notice:string };
const groups = [ ['employees','Sonio'], ['partners','Partner / Hersteller'], ['customers','Kunden'] ] as const;
const sumKnown = (events:Event[],key:'employees'|'partners'|'customers') => events.some(e=>e[key]!=null) ? events.reduce((n,e)=>n+(e[key]??0),0) : null;
const showDate = (date:string|null) => date ? new Date(date+'T12:00:00').toLocaleDateString('de-CH') : 'Datum nicht hinterlegt';

export function Events({demo}:{demo:boolean}) {
 const [source,setSource]=useState(''); const [year,setYear]=useState(''); const [month,setMonth]=useState(''); const [topic,setTopic]=useState(''); const [status,setStatus]=useState(''); const [exportOpen,setExportOpen]=useState(false); const [exportGroups,setExportGroups]=useState(true);
 const q=useQuery({queryKey:['events-aggregate'],queryFn:()=>api<Data>('/events'),enabled:!demo,refetchInterval:60000});
 if(demo) return <section className="panel"><h2>Events verbinden Menschen.</h2><p>Die öffentliche Demo enthält keine echten Event- oder Anmeldedaten.</p></section>;
 if(q.isPending) return <p role="status">Eventübersicht wird geladen …</p>;
 if(q.isError) return <section className="panel" role="alert"><h2>Events konnten nicht geladen werden.</h2><button className="button" onClick={()=>q.refetch()}>Erneut laden</button></section>;
 const snapshot=q.data.snapshot;
 if(!snapshot) return <section className="panel"><h2>Die Eventübersicht ist vorbereitet.</h2><p>Noch kein aggregierter Datenstand vorhanden. Es werden ausschliesslich Eventinformationen und Summen importiert.</p></section>;
 const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Zurich'}).format(new Date());
 const events=snapshot.events.filter(e=>(!source||e.source===source)&&(!year||e.date?.startsWith(year))&&(!month||e.date?.slice(5,7)===month)&&(!topic||e.topic===topic)&&(!status||(!!e.date&&(status==='upcoming'?e.date>=today:e.date<today)))).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||a.title.localeCompare(b.title));
 const years=[...new Set(snapshot.events.flatMap(e=>e.date?[e.date.slice(0,4)]:[]))].sort().reverse();
 const stamp=new Date(snapshot.observed_at).toLocaleString('de-CH',{timeZone:'Europe/Zurich'});
 const total=events.reduce((n,e)=>n+(e.registrations??e.responses??0),0);
 const missingTotal=events.some(e=>e.registrations===null&&e.responses===null);
 const knownTotals=events.filter(e=>e.registrations!==null||e.responses!==null).length;
 const unverified=events.some(e=>e.registrations===null);
 const exportCSV=()=>{saveCSV('sonio-events.csv',[
 ['Event','Quelle','Datum','Zeit','Ort','Thema','Formularantworten','Bestätigte Anmeldezahl','Zoom-Teilnahme-Einträge','Aufzeichnungsaufrufe',...(exportGroups?['Sonio','Partner / Hersteller','Kunden']:[]),'Datenstand (Europe/Zurich)','Quelle','Zeitbezug'],
 ...events.map(e=>[e.title,e.source,e.date,e.time,e.location,e.topic,e.responses,e.registrations,e.attendees,e.recording_views,...(exportGroups?[e.employees,e.partners,e.customers]:[]),stamp,snapshot.source,'Gesamtstand je Event'])]);setExportOpen(false)};
 return <div className="events-cockpit">
  <p className="events-intro">Begegnungen schaffen Beziehungen. Die Eventübersicht zeigt die Resonanz der Veranstaltungen – von der Anmeldung bis zur Zusammensetzung des Publikums.</p>
  <div className="section-heading"><div><h2>Events & Anmeldungen</h2><p>{events.length} Events / Formulare im gewählten Zeitraum <PeriodInfo label="Eventzeitraum und Datenstand">Die Auswahl bezieht sich auf das Eventdatum. Zahlen zeigen den erfassten Gesamtstand pro Formular. Mehrere Eventanmeldungen können von derselben Person stammen.</PeriodInfo></p></div><div className="events-actions"><button className="button" onClick={()=>q.refetch()} disabled={q.isFetching}><RefreshCw size={16}/> {q.isFetching?'Wird geladen …':'Daten aktualisieren'}</button><button className="button" onClick={()=>setExportOpen(!exportOpen)} aria-expanded={exportOpen}><Download size={16}/> CSV herunterladen</button></div></div>
  {exportOpen&&<div className="events-export"><strong>Export: aktuell gefilterte Events</strong><label><input type="checkbox" checked={exportGroups} onChange={e=>setExportGroups(e.target.checked)}/> Gruppenzahlen einschliessen</label><button className="button primary" onClick={exportCSV}>CSV erstellen</button></div>}
  <div className="events-filters"><CalendarDays size={20}/><label>Quelle<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Alle Quellen</option><option>Microsoft Forms</option><option>Zoom</option></select></label><label>Jahr<select value={year} onChange={e=>setYear(e.target.value)}><option value="">Alle Jahre</option>{years.map(y=><option key={y}>{y}</option>)}</select></label><label>Monat<select value={month} onChange={e=>setMonth(e.target.value)}><option value="">Ganzes Jahr</option>{Array.from({length:12},(_,i)=><option key={i} value={String(i+1).padStart(2,'0')}>{new Date(2026,i,1).toLocaleString('de-CH',{month:'long'})}</option>)}</select></label><label>Thema<select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">Alle Themen</option>{[...new Set(snapshot.events.map(e=>e.topic))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Alle Events</option><option value="upcoming">Bevorstehend</option><option value="past">Vergangen</option></select></label></div>
  <div className="events-kpis"><article><h3>Anmeldungen <PeriodInfo label="Anmeldungen erklärt">{unverified?'Vorläufige Zählbasis: Formularantworten. Nicht dedupliziert; Begleitpersonen und tatsächliche Teilnahme sind nicht verifiziert.':'Bestätigte Anmeldezahl je Event. Keine eindeutige Personenanzahl über mehrere Events.'}</PeriodInfo></h3><strong>{knownTotals?number(total):"—"}</strong><span>{missingTotal?`Teilstand: ${knownTotals} von ${events.length} Events`:unverified?'Zählbasis: Formularantworten':'Erfasster Gesamtstand'}</span></article>{groups.map(([key,label])=><article key={key}><h3>{label} <PeriodInfo label={`${label}: Erklärung`}>Anmeldungen mit bestätigter Zuordnung zu {label}. Ohne verlässliche Kategorie bleibt der Wert offen; aus Firmennamen wird keine Gruppe geraten.</PeriodInfo></h3><strong>{number(sumKnown(events,key))}</strong><span>{sumKnown(events,key)===null?'Zuordnung fehlt':events.every(e=>e[key]!==null)?'Anmeldungen':`Teilstand: ${events.filter(e=>e[key]!==null).length} von ${events.length} Events`}</span></article>)}</div>
  <p className="events-source">Stand: {stamp} · {snapshot.source}. {q.data.notice} Der Aktualisieren-Button lädt den zuletzt hinterlegten Stand.</p>
  {events.length===0&&<p className="panel">Für diese Auswahl sind keine Events hinterlegt.</p>}{(!source||source==='Zoom')&&<p className="events-source">Zoom: Aufzeichnungsarchiv ab 01.01.2024 geprüft. Die Liste umfasst erhaltene Aufzeichnungen und belegte Berichte; eine vollständige Historie gelöschter oder nicht aufgezeichneter Webinare ist damit nicht nachgewiesen.</p>}
  <div className="events-grid">{events.map(e=><article className="event-card" key={e.id}>
   {e.image_url&&<img className="event-image" src={e.image_url} alt={`Eventmotiv: ${e.title}`} loading="lazy" onError={ev=>{ev.currentTarget.style.display='none'}}/>}
   <div className="event-copy"><div className="event-meta"><span className="event-source-badge">{e.source}</span><span>{e.topic}</span><span>{e.duplicate_candidate?'Zusätzliches Formular':e.date?(e.date>=today?'Bevorstehend':'Vergangen'):'Datum offen'}</span></div><h3>{e.title}</h3><p>{e.description}</p><p className="event-date"><CalendarDays size={16}/>{showDate(e.date)} {e.time&&`· ${e.time}`}</p><p className="event-location"><MapPin size={16}/>{e.location||'Ort noch offen'}</p>
   {e.source==='Zoom'&&<dl className="event-stats event-zoom-stats"><div><dt>Live-Teilnahmen <PeriodInfo label="Zoom-Teilnahmen erklärt">Zahl aus dem Zoom-Verlaufsbericht. Wiederholte Beitritte und Veranstalter können enthalten sein; nicht als eindeutige Kundenanzahl interpretieren.</PeriodInfo></dt><dd>{number(e.attendees)}</dd></div><div><dt>Aufzeichnungsaufrufe <PeriodInfo label="Aufzeichnungsaufrufe erklärt">Aufrufe der gespeicherten Zoom-Aufzeichnung. Keine Live-Teilnahmen und keine eindeutigen Personen.</PeriodInfo></dt><dd>{number(e.recording_views)}</dd></div></dl>}<dl className="event-stats"><div><dt>Anmeldungen <PeriodInfo label={`Zählbasis ${e.title}`}>{e.registrations===null?'Formularantworten, keine bestätigte Personenanzahl.':'Verifizierte Anmeldezahl.'} {e.includes_companions?'Das Formular erfasst Begleitpersonen; diese sind in der Antwortzahl nicht separat berücksichtigt.':''}</PeriodInfo></dt><dd>{number(e.registrations??e.responses)}</dd></div>{groups.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{number(e[key])}</dd></div>)}</dl>
   <details><summary>Eventdetails & Datenbasis</summary><p>{e.data_note}</p><p>Quelle: {e.source}. {e.attendees!==null?`Zoom-Teilnahme-Einträge: ${number(e.attendees)}.`:"Tatsächliche Teilnahme nicht erfasst."}</p><p>{e.responses!==null?`${e.responses} Formularantworten. `:""} {e.registrations===null?'Personenzahl nicht bestätigt. ':''}{e.employees===null?'Gruppenzuordnung nicht verfügbar.':`${(e.registrations??e.responses??0)-e.employees-(e.partners??0)-(e.customers??0)} Anmeldungen nicht zugeordnet.`}</p>{e.includes_companions&&<p>Begleitpersonen werden im Formular abgefragt. Ohne aggregierte Personenzahl wird keine Teilnehmerzahl daraus abgeleitet.</p>}{e.capacity&&e.registrations!==null&&<p>Auslastung: {number(e.registrations/e.capacity*100)} % von {number(e.capacity)} Plätzen.</p>}{e.timeline.length?<div className="event-timeline"><h4>Anmeldungen im Verlauf</h4><ResponsiveContainer width="100%" height={180}><LineChart data={e.timeline}><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><Line dataKey="registrations" name="Anmeldungen" stroke="#0075d9" strokeWidth={2}/></LineChart></ResponsiveContainer></div>:<p>Für den Anmeldeverlauf fehlen aggregierte Tageszahlen.</p>}<small>Datenstand: {stamp}</small></details></div>
  </article>)}</div>
  <RecommendationTeaser/>
  <EditorialQuote portrait={asset('brand/portraits/tina-turner-v1.png')} text="It’s for the people and it’s for the song and it’s for the moment." author="Tina Turner" role="Sängerin und Bühnenikone" source="https://www.cbsnews.com/news/proud-tina-a-life-well-lived/"/>
 </div>;
}
