import {BenchmarkNote} from './BenchmarkNote';
import {googleAdsBenchmark} from '../benchmarks';
import {MetricHelp} from './MetricHelp';
import {adsComparison,type AdsComparison,type AdsComparisonData} from "../googleAdsComparison";
import {useState,useRef} from 'react';
import {useQuery} from '@tanstack/react-query';
import {RefreshCw,Download} from 'lucide-react';
import {api,number} from '../api';
import {asset} from '../staticDemo';
import {saveCSV} from '../csv';
import {PeriodInfo} from './PeriodInfo';
import {EditorialQuote} from './EditorialQuote';
import {RecommendationTeaser} from './RecommendationTeaser';
import '../google-ads.css';
type Creative={id:string;image:string|null;title:string;description:string};
type Campaign={id:string;name:string;type:string;status:string;currency:string;creatives:Creative[]}&Record<'impressions'|'clicks'|'conversions'|'spend'|'ctr'|'cpc'|'cpa'|'conversion_rate',number|null>;
type Report={campaigns:Campaign[];start:string;end:string;updated_at:string;warning?:string;comparison_data?:AdsComparisonData};
const labels={clicks:'Klicks',conversions:'Erfasste Zielaktionen',cpa:'Kosten / Zielaktion',spend:'Ausgaben',impressions:'Impressionen',ctr:'Klickrate (CTR)',cpc:'Ø Klickpreis',conversion_rate:'Conversion-Rate'};
type Key=keyof typeof labels;
const help:Record<Key,string>={clicks:'Klicks auf Anzeigen im gewählten Zeitraum. Ein Klick ist noch kein qualifizierter Website-Besuch.',conversions:'Von Google Ads zugerechnete Conversions. Welche Aktionen dahinterstehen, muss fachlich geprüft werden; sie sind nicht automatisch Leads. Attribution kann Bruchteile ergeben.',cpa:'Ausgaben geteilt durch die erfassten Zielaktionen. Nur bei vergleichbaren Conversion-Zielen sinnvoll. Ohne Zielaktionen wird kein Wert berechnet.',spend:'Werbeausgaben im gewählten Zeitraum, in der Kontowährung. Keine Agentur- oder Produktionskosten.',impressions:'So oft wurden Anzeigen eingeblendet. Mehrere Einblendungen können dieselbe Person betreffen.',ctr:'Klicks geteilt durch Impressionen. Die Klickrate zeigt Resonanz, nicht die Qualität der späteren Anfrage. Kampagnentyp und Datenmenge beachten.',cpc:'Ausgaben geteilt durch Klicks. Ein günstiger Klick ist nicht automatisch ein wertvoller Kontakt.',conversion_rate:'Von Google Ads gemeldeter Anteil der relevanten Anzeigeninteraktionen, die zu einer Conversion führen. Je nach Anzeigenformat sind Interaktionen nicht nur Klicks.'};
const types:Record<string,string>={SEARCH:'Suche',DISPLAY:'Display',VIDEO:'Video',PERFORMANCE_MAX:'Performance Max',DEMAND_GEN:'Demand Gen',SHOPPING:'Shopping'};
const format=(v:number|null,k:Key,currency='CHF')=>v==null?'—':number(v,['spend','cpa','cpc'].includes(k)?currency:'count')+(['ctr','conversion_rate'].includes(k)?' %':'');
function Metric({k,value,currency,comparison:c,campaignType}:{campaignType?:string;k:Key;value:number|null;currency:string;comparison?:AdsComparison}){
 const current=c?.current[k],previous=c?.previous[k];
 const delta=typeof current==='number'&&typeof previous==='number'&&previous>0?(current-previous)/previous*100:null;
 return <div className="gad-metric"><dt><b>{labels[k]}</b>{c&&<PeriodInfo label={`${labels[k]} erklärt`}>{help[k]}</PeriodInfo>}</dt><dd>{format(value,k,currency)}</dd>{value!=null&&campaignType&&<BenchmarkNote benchmark={googleAdsBenchmark(campaignType,k)}/>}{c&&<div className="gad-tendency comparison-data-info"><span data-trend={delta===null||delta===0?"neutral":delta>0?"up":"down"}>{delta===null ? 'Kein belastbarer Vergleich' : `${delta>0?'+':''}${number(delta)} % zum Vormonat`}</span><PeriodInfo label={`${labels[k]}: Vormonatsvergleich erklärt`}>{c.reason || `Vergleich ${c.start} bis ${c.end} mit ${c.previous_start} bis ${c.previous_end}. Vergleichswerte: ${format(current??null,k,currency)} gegenüber ${format(previous??null,k,currency)}.`}{k==='cpa'?' Kosten pro Zielaktion werden aus den gesamten Ausgaben geteilt durch sämtliche Zielaktionen berechnet. Ohne Zielaktionen kein CPA.':''}{previous===0?' Bei einem Vorwert von 0 ist keine prozentuale Veränderung definiert.':''}</PeriodInfo></div>}</div>}

function Preview({c,compact=false}:{c:Campaign;compact?:boolean}){const [index,setIndex]=useState(0);const ad=c.creatives[index]||c.creatives[0];return <div className={`gad-preview ${compact?'is-compact':''}`}>{ad?.image?<img src={ad.image} alt={`Beispielmotiv der Kampagne: ${c.name}`} loading={compact?"eager":"lazy"} onError={e=>{e.currentTarget.hidden=true}}/>:<div className="gad-text-ad"><small>{ad?'Textvorschau · mögliche Kombination':'Anzeigenvorschau nicht verfügbar'}</small><strong>{ad?.title||c.name}</strong>{!compact&&<p>{ad?.description||'Für diesen Anzeigentyp wurde kein Motiv geliefert.'}</p>}</div>}{!compact&&ad?.image&&<small className="gad-motif-caption">Beispielmotiv aus den Kampagnen-Assets</small>}{!compact&&c.creatives.length>1&&<label>Anzeigenmotiv<select aria-label={`Anzeigenmotiv für ${c.name}`} value={index} onChange={e=>setIndex(Number(e.target.value))}>{c.creatives.map((a,i)=><option key={a.id} value={i}>Anzeige {i+1}</option>)}</select></label>}</div>}
export function GoogleAdsHero(){return <><div className="marketing-mast"><h1>Google Ads Cockpit.</h1></div><section className="marketing-hero"><img src={asset('brand/sonio-blog-header.jpg')} alt="Berglandschaft mit Fahrer und Zielflagge"/><div><h2>Interesse wecken. Wirkung verstehen.</h2><p>Kampagnen einordnen. Budget bewusst einsetzen.</p></div></section></>}
export function GoogleAds({month,onMonth,demo}:{month:string;onMonth:(m:string)=>void;demo:boolean}){
 const [type,setType]=useState('all');const [includeInactive,setIncludeInactive]=useState(false);const refresh=useRef(false);
 const q=useQuery({queryKey:['google-ads-campaigns',month,demo],queryFn:()=>api<Report>(`/google-ads/campaigns?month=${month}&refresh=${refresh.current}`),enabled:!demo});
 const data=q.data;const campaigns=(data?.campaigns||[]).filter(c=>(type==='all'||c.type===type)&&(includeInactive||Boolean(c.impressions||c.clicks||c.spend||c.conversions)));const currency=campaigns[0]?.currency||'CHF';
 const sum=(k:Key)=>campaigns.length&&campaigns.every(c=>typeof c[k]==='number'&&Number.isFinite(c[k]))?campaigns.reduce((n,c)=>n+c[k]!,0):null;
 const comparison=adsComparison(data?.comparison_data,campaigns.map(c=>c.id),currency);
 const clicks=sum('clicks'),conversions=sum('conversions'),spend=sum('spend');
 const current=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Zurich',year:'numeric',month:'2-digit'}).format(new Date());
 const months=Array.from({length:12},(_,i)=>{const d=new Date(current+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()-i);return d.toISOString().slice(0,7)});if(!months.includes(month))months.push(month);
 const rankings=(key:'clicks'|'ctr')=>{const sorted=[...campaigns].filter(c=>c[key]!=null&&Boolean(c.impressions)).sort((a,b)=>b[key]!-a[key]!);const max=Math.max(1,...sorted.map(c=>c[key]!));const lead=sorted[0];const clickLeader=[...sorted].sort((a,b)=>(b.clicks??0)-(a.clicks??0))[0];return <section className="gad-ranking"><h2 className="gad-chart-heading">{key==='clicks'?'Welche Kampagne bewegt?':'Top CTR.'}<PeriodInfo label={key==='clicks'?'Klick-Ranking erklärt':'Top CTR erklärt'}>{key==='clicks'?'Ranking nach absoluten Klicks im ausgewählten Zeitraum. Mehr Budget oder längere Auslieferung können mehr Klicks ermöglichen. Dies ist kein Effizienzranking.':'CTR = Klicks geteilt durch Impressionen. Eine hohe Klickrate bedeutet nicht automatisch viele Zugriffe oder qualifizierte Anfragen. Kampagnentyp, Zielgruppe und Datenmenge beeinflussen die Einordnung. Kleine Datenmengen sind besonders schwankungsanfällig; für einen faireren Vergleich den Kampagnentyp eingrenzen.'}</PeriodInfo></h2><p>{key==='clicks'?'Kampagnen nach Klicks':'Kampagnen nach Klickrate (CTR)'} · Details beim Darüberfahren.</p>{sorted.map(c=><div className="gad-rank" key={c.id}><button type="button" onClick={()=>document.getElementById(`gad-${c.id}`)?.scrollIntoView({behavior:'smooth',block:'center'})}><span>{c.name}</span><strong>{format(c[key],key)}</strong><span className="gad-track"><span style={{width:`${c[key]!/max*100}%`}}/></span></button><div className="gad-hover" role="tooltip"><Preview c={c} compact/><strong>{c.name}</strong><p>{number(c.impressions,'count')} Impressionen · {number(c.clicks,'count')} Klicks<br/>{format(c.ctr,'ctr')} CTR · {format(c.spend,'spend',c.currency)} Ausgaben</p></div></div>)}{!sorted.length&&<p>Keine Kampagnenwerte für diese Auswahl.</p>}{key==='ctr'&&lead&&lead.ctr!>0&&<p className="gad-ranking-context"><strong>Die Klickrate einordnen.</strong> {lead.name} liegt in dieser Auswahl mit {format(lead.ctr,'ctr')} vorn: {number(lead.clicks,'count')} Klicks bei {number(lead.impressions,'count')} Einblendungen. {clickLeader&&clickLeader.id!==lead.id?'Die höchste Klickrate bedeutet hier nicht das grösste Klickvolumen. ':''}Der Klickanteil deutet auf Resonanz bei den erreichten Personen hin. Ob daraus wertvolle Besuche oder Anfragen entstehen, lässt sich daraus allein nicht ableiten.</p>}</section>};
 return <div className="gad-page"><p className="directory-intro">Google Ads macht Angebote dort sichtbar, wo Interesse entsteht. Diese Übersicht verbindet Aufmerksamkeit, Zielaktionen und Kosten – damit Marketing die nächsten Schritte fundiert priorisieren kann.</p><div className="section-heading gad-toolbar"><div><h2>Google Ads im Überblick.</h2><label>Zeitraum <select aria-label="Google Ads Monat" value={month} onChange={e=>onMonth(e.target.value)}>{months.map(m=><option key={m} value={m}>{new Date(m+'-01T12:00:00').toLocaleDateString('de-CH',{month:'long',year:'numeric'})}</option>)}</select></label><PeriodInfo>Die grossen Kennzahlen zeigen den gewählten Monat. Die Tendenzen vergleichen gleich lange verfügbare Zeiträume mit dem Vormonat, ohne den laufenden Tag. Beide Seiten verwenden die aktuell ausgewählten Kampagnen und Filter. Die genauen Vergleichswerte stehen bei jeder Kennzahl. Die grosse Kennzahl kann neuere Daten enthalten. Grün zeigt eine Zunahme, Rot eine Abnahme. Bei Kosten bedeutet eine Zunahme nicht automatisch bessere Performance; Conversion-Ziele, Budget und Kampagnenmix beeinflussen die Einordnung. Conversions können nachträglich ergänzt werden.</PeriodInfo></div><div className="gad-actions"><button disabled={demo||q.isFetching} onClick={async()=>{refresh.current=true;try{await q.refetch()}finally{refresh.current=false}}}><RefreshCw size={15}/>Daten aktualisieren</button><button disabled={!campaigns.length} onClick={()=>saveCSV(`google-ads-${month}.csv`,[['Kampagne','Typ','Von','Bis','Währung','Datenstand',...Object.values(labels)],...campaigns.map(c=>[c.name,c.type,data?.start,data?.end,c.currency,data?.updated_at,...(Object.keys(labels) as Key[]).map(k=>c[k])])])}><Download size={15}/>CSV herunterladen</button></div></div>
 {demo&&<p role="status">Die öffentliche Demo enthält keine echten Google-Ads-Kampagnendetails.</p>}{q.isLoading&&<p role="status">Kampagnen werden geladen …</p>}{q.isError&&<p role="alert">Kampagnen konnten nicht geladen werden. Bitte erneut aktualisieren.</p>}{data?.warning&&<p role="status">{data.warning}</p>}
 <div className="gad-filter"><label>Kampagnentyp <select value={type} onChange={e=>setType(e.target.value)}><option value="all">Alle Kampagnentypen</option>{[...new Set(data?.campaigns.map(c=>c.type))].map(t=><option value={t} key={t}>{types[t]||t}</option>)}</select></label><label><input type="checkbox" checked={includeInactive} onChange={e=>setIncludeInactive(e.target.checked)}/> Auch ohne Auslieferung</label><span>{campaigns.length} Kampagnen{data&&` · Stand ${new Date(data.updated_at).toLocaleString('de-CH',{timeZone:'Europe/Zurich'})}`}</span></div>
 <dl className="gad-summary">{([['clicks',clicks],['conversions',conversions],['cpa',conversions&&spend!=null?spend/conversions:null],['spend',spend]] as [Key,number|null][]).map(([k,v])=><Metric key={k} k={k} value={v} currency={currency} comparison={comparison}/>)}</dl><p className="gad-note">Zielaktionen gemäss Google Ads – noch keine fachliche Einstufung als qualifizierte Leads. Rankings beschreiben die Auswahl und bewerten unterschiedliche Kampagnenziele nicht pauschal.</p>
 <div className="gad-rankings">{rankings('clicks')}{rankings('ctr')}</div><h2 className="gad-chart-heading">Jede Kampagne im Blick.<PeriodInfo label="Kampagnenstatus und Anzeigenvorschau erklärt">Der Status zeigt den aktuellen Zustand, nicht zwingend den Zustand im ausgewählten Monat. Bilder sind Beispielmotive aus den Kampagnen-Assets; Textvorschauen sind mögliche Kombinationen. Alle Kennzahlen beziehen sich auf die gesamte Kampagne, nicht nur auf das gezeigte Motiv.</PeriodInfo></h2><p>{campaigns.length} Kampagnen im gewählten Zeitraum. Kennzahlen und Anzeigenvorschauen je Kampagne.</p><MetricHelp label="Kampagnenkennzahlen erklärt" entries={Object.entries(labels).map(([key,label])=>({key,label,text:help[key as Key]}))}/><div className="gad-campaigns">{campaigns.map(c=><article id={`gad-${c.id}`} key={c.id}><Preview c={c}/><div className="gad-campaign-body"><small>{types[c.type]||c.type} · {c.status==='ENABLED'?'Aktiv':c.status==='PAUSED'?'Pausiert':c.status==='REMOVED'?'Entfernt':c.status}</small><h3>{c.name}</h3><dl>{(['impressions','clicks','ctr','spend'] as Key[]).map(k=><Metric key={k} k={k} value={c[k]} currency={c.currency} campaignType={c.type}/>)}</dl><details><summary>Weitere Kennzahlen</summary><dl>{(['conversions','cpa','cpc','conversion_rate'] as Key[]).map(k=><Metric key={k} k={k} value={c[k]} currency={c.currency} campaignType={c.type}/>)}</dl></details></div></article>)}</div><RecommendationTeaser/><EditorialQuote text="Failure taught me things about myself that I could have learned no other way." author="J. K. Rowling" role="Schriftstellerin" source="https://news.harvard.edu/gazette/story/2008/06/text-of-j-k-rowling-speech/" portrait={asset('brand/portraits/jk-rowling-v2.png')}/></div>
}
