import {number} from '../api';
import {PeriodInfo} from './PeriodInfo';
import type {Campaign} from './GoogleAds';
export type ConversionAction={id:string;name:string;group:'forms'|'downloads'|'other';conversions:number;all_conversions:number};
export function GoogleAdsConversions({campaigns,warning}:{campaigns:Campaign[];warning?:string}){
 const ready=campaigns.length>0&&campaigns.every(c=>Array.isArray(c.conversion_actions));
 const actions=campaigns.flatMap(c=>c.conversion_actions||[]);
 const groups=[['forms','Formularübermittlungen','Über Google-Ads-Leadformulare übermittelte Anfragen. Keine bestätigten qualifizierten Leads und keine garantierte Anzahl eindeutiger Personen.'],['downloads','Downloads · Interesse','Google Ads zugerechnete file_download-Conversions. Ein Download signalisiert Interesse, ist aber keine Kontaktanfrage. Attribution kann Bruchteile ergeben.'],['other','Weitere Zielaktionen','Weitere in der Conversion-Summe enthaltene Aktionen. Kontakt- und Health-Check-Ereignisse bleiben hier, bis ihre Auslöser geprüft sind.']] as const;
 return <section className="gad-conversion-breakdown" aria-label="Zielaktionen aufgeschlüsselt"><h3>Was hinter den Zielaktionen steckt.</h3><dl>{groups.map(([key,label,help])=><div key={key}><dt>{label}<PeriodInfo label={`${label} erklärt`}>{help} Gleicher Monat und gleiche Kampagnenauswahl wie oben. Gezählt werden Beiträge zur Kennzahl «Conversions», nicht zur erweiterten Kennzahl «Alle Conversions».</PeriodInfo></dt><dd>{ready?number(actions.filter(a=>a.group===key).reduce((s,a)=>s+a.conversions,0)):'—'}</dd></div>)}</dl>{!ready&&<p role="status">{warning||'Die Aufschlüsselung ist noch nicht geladen. Bitte Daten aktualisieren.'}</p>}<details><summary>Messung und einzelne Aktionen</summary><p>Die drei Gruppen ergeben zusammen die erfassten Zielaktionen. Qualifizierte Leads sind noch nicht erfasst; dafür braucht es eine bestätigte Rückmeldung von Marketing oder Sales. Die Zahlen belegen weder Kontaktqualität noch einen Geschäftsabschluss.</p>{ready&&<ul>{campaigns.flatMap(c=>(c.conversion_actions||[]).map(a=><li key={`${c.id}:${a.id}`}><strong>{c.name}</strong> · {a.name}: {number(a.conversions)} Zielaktionen; {number(a.all_conversions)} unter «Alle Conversions».</li>))}</ul>}<p>Weitere Interaktionen können nur unter «Alle Conversions» auftauchen. Sie werden nicht zur oberen Summe addiert. Zeitbezug: Anzeigeninteraktion, nicht zwingend Datum der Formularübermittlung.</p></details></section>;
}
