import {reportPageImage} from '../reportImages';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {ExternalLink, Image as ImageIcon} from 'lucide-react';
import {api,number,monthName} from '../api';
import {PeriodInfo} from './PeriodInfo';
import type {Dashboard} from '../types';
import './sales-report.css';
import {salesPortraits} from '../salesPortraits';
import type {PostsResponse} from './PerformanceExplorer';
import {readablePostTitle} from '../comparison';
type Page={kind?:string|null;path:string;url:string;title:string;image:string|null;current:Record<string,number|null>|null;previous:Record<string,number|null>|null};
type Pages={pages:Page[];start:string;end:string;previous_start:string;previous_end:string;updated_at:string;warning?:string;thresholded:boolean};
type Campaign={id:string;name:string;clicks:number|null;impressions:number|null;ctr:number|null;creatives?:{image:string|null}[];image_url?:string;values?:Record<string,number>};
type Ads={campaigns:Campaign[];start:string;end:string;updated_at?:string;last_success?:string;warning?:string;status?:string;message?:string};
function Picture({src,title}:{src?:string|null;title:string}){const [failed,setFailed]=useState(false);return src&&!failed?<img src={src} alt={title} onError={()=>setFailed(true)}/>:<div className="sales-image-empty"><ImageIcon size={28}/><span>Kein Vorschaubild verfügbar</span></div>}
const hasValue=(n:unknown):n is number=>typeof n==='number'&&Number.isFinite(n)&&n>=0;
export function SalesReport({data}:{data:Dashboard}){
 const [platform,setPlatform]=useState<'google'|'linkedin'>('google');
 const [showAll,setShowAll]=useState(false);
 const [allPages,setAllPages]=useState(false);
 const pages=useQuery({queryKey:['sales-pages',data.month],queryFn:()=>api<Pages>(`/sales-report/pages?month=${data.month}`),enabled:!data.demo,staleTime:3600000});
 const ads=useQuery({queryKey:['sales-ads','google',data.month],queryFn:()=>api<Ads>(`/google-ads/campaigns?month=${data.month}`),enabled:!data.demo&&platform==='google',staleTime:3600000});
 const portraitTotals=useQuery({queryKey:['sales-portrait-totals'],queryFn:()=>api<Pages>(`/analytics/areas?area=profile&period=all`),enabled:!data.demo,staleTime:3600000});
 const ranked=(pages.data?.pages||[]).map(p=>({...p,image:reportPageImage(p.path,p.image),catalogImage:p.image})).filter(p=>!/^\/(?:fr-ch\/)?services\/support(?:\/|$)/i.test(p.path)).filter(p=>allPages||p.kind||p.catalogImage).filter(p=>hasValue(p.current?.screenPageViews)&&p.current!.screenPageViews!>0).sort((a,b)=>b.current!.screenPageViews!-a.current!.screenPageViews!||a.path.localeCompare(b.path));
 const campaigns=(ads.data?.campaigns||[]).map(c=>({...c,clicks:c.values?.clicks??c.clicks,impressions:c.values?.impressions??c.impressions})).filter(c=>hasValue(c.clicks)&&c.clicks>0).sort((a,b)=>b.clicks!-a.clicks!||a.name.localeCompare(b.name));
 const lead=ranked[0], best=campaigns[0];
 return <div className="sales-report">
 {data.demo?<p className="sales-feedback">In der öffentlichen Demo werden keine geschützten Inhaltsdaten geladen.</p>:null}
 <section className="sales-section"><header><div><h3>Diese Inhalte ziehen Aufmerksamkeit an.</h3><p>Website · {monthName(data.month)} · nach Seitenaufrufen</p></div><PeriodInfo label="Website-Ranking erklärt">Monatswerte unabhängig vom Veröffentlichungsdatum. Fachinhalte umfasst erkannte Blog-, News-, Kompetenz- und Customer-Story-Seiten sowie Seiten aus dem vorhandenen Bildkatalog. Alle Webseiten enthält zusätzlich Einstieg, Karriere, Kontakt und weitere Pfade. Seitenaufrufe sind keine eindeutigen Besucher und kein Nachweis für Kaufinteresse. Vorschauen stammen aus dem vorhandenen Website-Katalog. Datenstand: {pages.data?.updated_at?new Date(pages.data.updated_at).toLocaleString('de-CH'):'noch nicht verfügbar'}. Zeitraum: {pages.data?.start} bis {pages.data?.end}.</PeriodInfo></header>
 <div className="sales-platforms" role="group" aria-label="Website-Auswahl"><button aria-pressed={!allPages} onClick={()=>{setAllPages(false);setShowAll(false)}}>Fachinhalte & Porträts</button><button aria-pressed={allPages} onClick={()=>{setAllPages(true);setShowAll(false)}}>Alle Webseiten</button></div>
 {pages.isLoading&&!data.demo?<p role="status">Website-Inhalte werden geladen …</p>:pages.isError?<div className="sales-feedback" role="alert">Website-Ranking konnte nicht geladen werden. <button onClick={()=>pages.refetch()}>Erneut laden</button></div>:null}
 {pages.data?.warning&&<p role="status" className="sales-feedback">{pages.data.warning}</p>}{pages.data?.thresholded&&<p className="sales-feedback">Google begrenzt Teile der Daten. Das Ranking kann unvollständig sein.</p>}
 {lead?<><div className="sales-spotlight"><a href={lead.url} target="_blank" rel="noreferrer" className="sales-feature"><Picture key={lead.image} src={lead.image} title={lead.title}/><div><span>Am häufigsten aufgerufen</span><h4>{lead.title}</h4><strong>{number(lead.current!.screenPageViews)} <small>Aufrufe</small></strong><span>Inhalt öffnen <ExternalLink size={14}/></span></div></a><div className="sales-ranking">{ranked.slice(0,5).map((p,i)=><a key={p.path} href={p.url} target="_blank" rel="noreferrer"><span className="sales-rank-position">{i+1}</span>{p.image&&<img className="sales-rank-thumb" src={p.image} alt="" loading="lazy"/>}<div><b>{p.title}</b><span className="sales-track"><span style={{width:`${p.current!.screenPageViews!/lead.current!.screenPageViews!*100}%`}}/></span></div><strong>{number(p.current!.screenPageViews)}</strong></a>)}</div></div><p className="sales-feedback"><b>Für den nächsten Austausch:</b> «{lead.title}» liegt bei den Seitenaufrufen vorn. Den Inhalt als Gesprächseinstieg prüfen – ob er zur konkreten Kundensituation passt, bleibt entscheidend.</p><div className="sales-content-grid">{ranked.slice(0,showAll?ranked.length:4).map(p=><a href={p.url} target="_blank" rel="noreferrer" key={p.path}><Picture key={p.image} src={p.image} title={p.title}/><div><h4>{p.title}</h4><p><b>{number(p.current?.screenPageViews)}</b> Aufrufe · <b>{number(p.current?.totalUsers)}</b> Besucher</p><span>Inhalt ansehen <ExternalLink size={13}/></span></div></a>)}</div>{ranked.length>4&&<button className="button secondary" onClick={()=>setShowAll(!showAll)}>{showAll?'Weniger Inhalte zeigen':`Alle ${ranked.length} Inhalte zeigen`}</button>}</>:!pages.isLoading&&!pages.isError&&!data.demo?<p className="sales-feedback">Für diesen Monat sind noch keine Seiten mit gemeldeten Aufrufen verfügbar.</p>:null}
 </section>
 <section className="sales-section"><header><div><h3>Was weckt Interesse?</h3><p>{platform==='google'?`${monthName(data.month)} · Google-Ads-Kampagnen nach Klicks`:`Beiträge aus ${monthName(data.month)} · Gesamtwerte seit Veröffentlichung`}</p></div>{platform==='google'&&<PeriodInfo label="Anzeigen-Ranking erklärt">Die Rangfolge zeigt Klickvolumen, keine Qualitätsbewertung. Budget, Zielgruppe und Auslieferungsdauer beeinflussen es. Zeitraum: {ads.data?.start} bis {ads.data?.end}. Stand: {ads.data?.updated_at||ads.data?.last_success||'noch nicht verfügbar'}.</PeriodInfo>}</header>
 <div className="sales-platforms" role="group" aria-label="Kanal für Klick-Ranking"><button aria-pressed={platform==='google'} onClick={()=>setPlatform('google')}>Google Ads</button><button aria-pressed={platform==='linkedin'} onClick={()=>setPlatform('linkedin')}>LinkedIn Organic</button></div>
 {platform==='linkedin'?<SalesOrganic month={data.month} demo={data.demo}/>:<>
 {ads.data?.warning&&<p className="sales-feedback">{ads.data.warning}</p>}{ads.data?.status&&ads.data.status!=='connected'&&<p className="sales-feedback">{ads.data.message}</p>}
 {ads.isLoading&&!data.demo?<p role="status">Kampagnen werden geladen …</p>:ads.isError?<p role="alert" className="sales-feedback">Anzeigenzahlen konnten nicht geladen werden. <button onClick={()=>ads.refetch()}>Erneut laden</button></p>:null}
 <div className="sales-ad-grid">{campaigns.slice(0,5).map((c,i)=><article key={c.id}><Picture src={c.image_url||c.creatives?.find(a=>a.image)?.image} title={c.name}/><div><span>Rang {i+1}</span><h4>{c.name}</h4><strong>{number(c.clicks)} <small>Klicks</small></strong><span className="sales-track"><span style={{width:`${c.clicks!/best!.clicks!*100}%`}}/></span><p>{number(c.impressions)} Einblendungen · {number(c.ctr)}{c.ctr!=null?' % CTR':''}</p></div></article>)}</div>
 {!campaigns.length&&!ads.isLoading&&!ads.isError&&!data.demo&&<p className="sales-feedback">Keine Kampagne mit gemeldeten Klicks in diesem Monat. Es werden keine älteren Gesamtzahlen eingesetzt.</p>}
 {best&&<p className="sales-feedback"><b>Gesprächsimpuls:</b> «{best.name}» erzielt in dieser Auswahl die meisten Klicks. Die Botschaft kann als Ausgangspunkt für ein passendes Kundengespräch dienen; Klicks allein belegen noch keine qualifizierte Nachfrage.</p>}
 </>}
 </section>
 <section className="sales-section"><header><div><h3>Die Menschen hinter den Gesprächen.</h3><p>Sales stellt sich vor · Videos für den persönlichen Einstieg</p></div><PeriodInfo label="Sales-Videos und Kennzahlen erklärt">Diese Videos stammen direkt von den öffentlichen Sonio-Vorstellungsseiten und bleiben unabhängig vom Berichtsmonat verfügbar. Die Zahl unter dem Video bezeichnet Seitenaufrufe im ausgewählten Monat, nicht Videoaufrufe. Gesamt zeigt die verfügbaren Seitenaufrufe seit Veröffentlichung bis zum letzten Datenstand. Der aktuelle Monat ist separat ausgewiesen und ist Teil des Gesamtstands, nicht zusätzlich zu addieren. Fehlende Messwerte bleiben als Strich sichtbar.</PeriodInfo></header>
 {portraitTotals.isError&&<p className="sales-feedback" role="alert">Gesamtzahlen konnten nicht geladen werden. <button onClick={()=>portraitTotals.refetch()}>Erneut laden</button></p>}{portraitTotals.data?.warning&&<p className="sales-feedback">{portraitTotals.data.warning}</p>}
 <div className="sales-portrait-grid">{salesPortraits.map(person=>{const page=pages.data?.pages.find(p=>p.path.replace(/\/$/,'')===person.path);const total=portraitTotals.data?.pages.find(p=>p.path.replace(/\/$/,'')===person.path);return <article key={person.path}><video controls playsInline preload="none" poster={person.image} aria-label={`Vorstellung von ${person.name}`} src={person.video}/><div><h4>{person.name}</h4><div className="sales-portrait-stats" aria-label={`Seitenaufrufe für ${person.name}`}><div><span>{monthName(data.month)}{data.partial&&pages.data?` bis ${Number(pages.data.end.slice(8))}.`:''}</span><strong>{pages.isLoading?'…':number(page?.current?.screenPageViews)}</strong></div><div><span>Gesamt seit Veröffentlichung</span><strong>{portraitTotals.isLoading&&!data.demo?'…':number(total?.current?.screenPageViews)}</strong></div><small>Seitenaufrufe · keine Videoaufrufe</small></div><a href={'https://www.sonio.com'+person.path} target="_blank" rel="noreferrer">Vorstellungsseite öffnen <ExternalLink size={14}/></a></div></article>})}</div></section>
 </div>
}

function SalesOrganic({month,demo}:{month:string;demo:boolean}){
 const q=useQuery({queryKey:['sales-organic',month],queryFn:()=>api<PostsResponse>(`/linkedin/posts?month=${month}`),enabled:!demo,staleTime:3600000});
 const posts=(q.data?.posts||[]).filter(p=>hasValue(p.metrics.clicks)).sort((a,b)=>b.metrics.clicks-a.metrics.clicks||a.id.localeCompare(b.id));
 const max=Math.max(1,...posts.map(p=>p.metrics.clicks));
 if(demo)return <p className="sales-feedback">In der Demo werden keine geschützten LinkedIn-Beiträge geladen.</p>;
 if(q.isLoading)return <p role="status">LinkedIn-Beiträge werden geladen …</p>;
 if(q.isError)return <p role="alert" className="sales-feedback">Beiträge konnten nicht geladen werden. <button onClick={()=>q.refetch()}>Erneut laden</button></p>;
 return <><p className="sales-organic-period">LinkedIn Organic · nach Klicks <PeriodInfo label="LinkedIn-Beitragsranking erklärt">Auswahl nach Veröffentlichungsmonat. Die Kennzahlen zeigen den zuletzt importierten Gesamtstand seit Veröffentlichung, keine Monatsleistung. LinkedIn-Klicks können innerhalb der Plattform bleiben und sind keine gesicherten Website-Klicks. Ältere Beiträge hatten mehr Zeit, Klicks zu sammeln. Beiträge ohne Klickmesswert werden nicht gerankt. Datenstand: {q.data?.last_success?new Date(q.data.last_success).toLocaleString('de-CH'):'nicht verfügbar'}.</PeriodInfo></p>
 {q.data?.status!=='connected'&&q.data?.message&&<p className="sales-feedback">{q.data.message}</p>}
 <div className="sales-ad-grid">{posts.slice(0,5).map((p,i)=><article key={p.id}><Picture key={p.image_url} src={p.image_url} title={readablePostTitle(p.title)}/><div><span>Rang {i+1} · {new Date(p.published_at).toLocaleDateString('de-CH')}</span><h4>{readablePostTitle(p.title)}</h4><strong>{number(p.metrics.clicks)} <small>LinkedIn-Klicks</small></strong><span className="sales-track"><span style={{width:`${p.metrics.clicks/max*100}%`}}/></span><p>{number(p.metrics.impressions)} Einblendungen · {number(p.metrics.likes)} Likes</p><a href={p.url} target="_blank" rel="noreferrer">Beitrag öffnen <ExternalLink size={13}/></a></div></article>)}</div>
 {!posts.length&&<p className="sales-feedback">Für Beiträge aus diesem Monat liegen noch keine Klickmesswerte vor. Fehlende Werte werden nicht als null dargestellt.</p>}
 {posts[0]?.metrics.clicks>0&&<p className="sales-feedback"><b>Für den nächsten Austausch:</b> «{readablePostTitle(posts[0].title)}» hat unter diesen Beiträgen bisher die meisten Klicks gesammelt. Als möglichen Gesprächseinstieg auf fachliche Relevanz prüfen.</p>}</>;
}
