import {useState,useRef} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api,number} from '../api';
import {asset} from '../staticDemo';
import {saveCSV} from '../csv';
import {PeriodInfo} from './PeriodInfo';
import {EditorialQuote} from './EditorialQuote';
import '../search-insights.css';
import {searchTopic,searchTopics,topicTotals,type SearchTopic} from '../searchTopics';
type Row={term:string;clicks:number;impressions:number;ctr:number|null;position?:number;spend?:number;conversions?:number;campaign?:string;type?:string;match?:string;currency?:string;pages?:{url:string;clicks:number}[]};
type Report={rows:Row[];notice:string;updated_at:string;start:string;end:string;warning?:string;totals?:{clicks:number;impressions:number}|null};
export function SearchHero(){return <><div className="marketing-mast"><h1>Suchbegriffe &amp; Potenziale.</h1></div><section className="marketing-hero"><img src={asset('brand/sonio-blog-header.jpg')} alt="Sonio Berglandschaft mit Fahrer und Zielflagge"/><div><h2>Verstehen, was Menschen suchen.</h2><p>Interesse erkennen. Relevante Themen entwickeln.</p></div></section></>}
export function SearchInsights({demo}:{demo:boolean}){
 const [month,setMonth]=useState('2026-09');const [source,setSource]=useState('organic');const [term,setTerm]=useState('');const [brand,setBrand]=useState('all');const [kind,setKind]=useState('all');const [topic,setTopic]=useState<SearchTopic|'all'>('all');const [limit,setLimit]=useState(10);const [metric,setMetric]=useState('clicks');const refresh=useRef(false);
 const q=useQuery({queryKey:['search-insights',month,source,demo],queryFn:()=>api<Report>(`/search-insights?month=${month}&source=${source}&refresh=${refresh.current}`),enabled:!demo});
 const filtered=(q.data?.rows||[]).filter(r=>(r.term+' '+(r.campaign||'')).toLowerCase().includes(term.toLowerCase())&&(brand==='all'||(brand==='brand')===/\bsonio\b/i.test(r.term))&&(kind==='all'||r.type===kind));
 const clusters=topicTotals(filtered);
 const rows=filtered.filter(r=>topic==='all'||searchTopic(r.term)===topic);
 const topicLabel=searchTopics.find(t=>t.id===topic)?.label||'Alle Themen';
 const sum=(key:'clicks'|'impressions'|'spend'|'conversions')=>rows.reduce((n,r)=>n+(r[key]??0),0);const clicks=sum('clicks'),impressions=sum('impressions'),spend=sum('spend');
 const sorted=[...rows].sort((a,b)=>((b[metric as keyof Row] as number)||0)-((a[metric as keyof Row] as number)||0));const top=sorted.slice(0,8);const max=Math.max(1,...top.map(r=>Number(r[metric as keyof Row]||0)));
 const potential=source==='organic'?[...rows].filter(r=>r.impressions>=100&&r.position!>=5&&r.position!<=20).sort((a,b)=>b.impressions-a.impressions).slice(0,4):[...rows].filter(r=>(r.spend||0)>0&&r.conversions===0).sort((a,b)=>(b.spend||0)-(a.spend||0)).slice(0,4);
 const current=new Date();const months=Array.from({length:12},(_,i)=>{const d=new Date(Date.UTC(current.getFullYear(),current.getMonth()-i,1));return d.toISOString().slice(0,7)});
 const pct=(a:number,b:number)=>b?number(a/b*100)+' %':'—';
 return <div className="search-workspace"><p className="directory-intro">Welche Begriffe bringen Sonio ins Gespräch? Organische und bezahlte Suche bleiben getrennt. Sichtbare Suchanfragen liefern die Grundlage für Content-Ideen und gezielte Marketingtests.</p><section className="search-controls" aria-label="Suchberichte eingrenzen"><div className="search-toolbar search-period"><label>Monat<select value={month} onChange={e=>{setMonth(e.target.value);setLimit(10)}}>{months.map(m=><option key={m} value={m}>{new Date(m+'-01T12:00:00Z').toLocaleDateString('de-CH',{month:'long',year:'numeric'})}</option>)}</select></label><PeriodInfo>Organische Suche: finale Google-Daten, möglicherweise verzögert, in Pacific Time. Ads: Kontoberichtszeitraum. Ein laufender Monat ist unvollständig.</PeriodInfo><div className="search-actions"><button disabled={demo||q.isFetching} onClick={async()=>{refresh.current=true;try{await q.refetch()}finally{refresh.current=false}}}>Daten aktualisieren</button><button disabled={!rows.length} onClick={()=>saveCSV(`suchbegriffe-${source}-${month}.csv`,[['Quelle','Thema','Begriff','Kampagne','Typ','Klicks','Impressionen','CTR (%)','Position','Ausgaben','Währung','Zielaktionen','Von','Bis','Stand'],...rows.map(r=>[source,searchTopics.find(t=>t.id===searchTopic(r.term))!.label,r.term,r.campaign,r.type,r.clicks,r.impressions,r.ctr,r.position,r.spend,r.currency,r.conversions,q.data?.start,q.data?.end,q.data?.updated_at])])}>CSV herunterladen</button></div></div><div className="search-source-heading"><h2>Welche Suche interessiert?</h2><p>Quelle wählen, danach die Auswahl eingrenzen.</p></div><div className="channel-selector" role="group" aria-label="Suchdaten auswählen">{[['organic','Organische Suche'],['paid','Bezahlte Suchanfragen'],['keywords','Gebuchte Keywords']].map(([id,label])=><button key={id} aria-pressed={source===id} className={source===id?'selected':''} onClick={()=>{setSource(id);setTopic('all');setMetric('clicks');setKind('all');setLimit(10)}}>{label}</button>)}</div>
 <div className="search-toolbar search-filters"><label>Suchbegriff oder Thema<input value={term} onChange={e=>{setTerm(e.target.value);setLimit(10)}} placeholder="z. B. Cloud, Storage, Workplace"/></label><label>Markenbezug<select value={brand} onChange={e=>setBrand(e.target.value)}><option value="all">Alle Begriffe</option><option value="brand">Mit Sonio</option><option value="other">Ohne Sonio</option></select></label><PeriodInfo>Regelbasierte Zuordnung: enthält das Wort Sonio. Schreibvarianten und andere Marken werden nicht automatisch erkannt.</PeriodInfo>{source!=='organic'&&<label>Kampagnentyp<select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Alle Typen</option>{[...new Set(q.data?.rows.map(r=>r.type))].map(t=><option key={t}>{t}</option>)}</select></label>}</div></section>
 {demo?<p>Keine echten Suchbegriffe in der öffentlichen Demo.</p>:q.isPending?<p role="status">Suchberichte werden geladen …</p>:q.isError?<p role="alert">Suchberichte derzeit nicht verfügbar. Bitte erneut aktualisieren.</p>:<><p className="search-note">{q.data?.notice}</p>{q.data?.warning&&<p role="alert">{q.data.warning}</p>}<section className="search-topics" aria-label="Themenbereiche"><div className="section-heading"><div><h2>Welche Themen bewegen?</h2><p>Ein Thema auswählen – Ranking, Details und Potenziale folgen dieser Auswahl.</p></div><PeriodInfo label="Themenzuordnung erklärt">Regelbasierte Zuordnung anhand des Suchbegriffs mit deutschen, französischen und englischen Synonymen. Fachthemen haben Vorrang vor Sonio und allgemeinen Service-Wörtern. Mehrdeutige Begriffe und nicht erkannte Namen bleiben unter «Weitere». Kampagnennamen werden nicht zur Zuordnung verwendet. Jede Zeile zählt genau einmal; dies ist keine KI-Klassifikation.</PeriodInfo></div><button className="search-topic-all" aria-pressed={topic==='all'} onClick={()=>{setTopic('all');setLimit(10)}}>Alle Themen · {number(filtered.length)} Berichtszeilen</button><div className="search-topic-grid">{clusters.map(t=><button key={t.id} aria-pressed={topic===t.id} onClick={()=>{setTopic(t.id);setLimit(10)}}><strong>{t.label}</strong><span>{number(t.count)} Berichtszeilen</span><span className="search-topic-values"><span><b>{t.count?number(t.clicks):'—'}</b> Klicks</span><span><b>{t.count?number(t.impressions):'—'}</b> Impressionen</span></span></button>)}</div><p className="search-note">Themensummen beziehen sich auf die gewählte Datenquelle und die Filter oben. Unklare Zuordnungen bleiben offen.</p></section><p className="search-topic-selection" role="status">{topicLabel} · {number(rows.length)} Berichtszeilen</p><dl className="search-kpis"><div><dt>Sichtbare Berichtszeilen <PeriodInfo>Ein Suchbegriff kann bei Ads in mehreren Kampagnen oder Anzeigengruppen vorkommen. Dies ist keine Anzahl eindeutiger Suchbegriffe.</PeriodInfo></dt><dd>{number(rows.length)}</dd></div><div><dt>Klicks der Auswahl <PeriodInfo>Klicks auf Suchergebnisse beziehungsweise Anzeigen in den sichtbaren Berichtszeilen. Wiederholte Klicks sind möglich; dies ist keine Anzahl Personen.</PeriodInfo></dt><dd>{rows.length?number(clicks):'—'}</dd></div><div><dt>Impressionen der Auswahl <PeriodInfo>Wie oft die Suchergebnisse beziehungsweise Anzeigen eingeblendet wurden. Eine Person kann mehrere Einblendungen erzeugen.</PeriodInfo></dt><dd>{rows.length?number(impressions):'—'}</dd></div><div><dt>Klickrate <PeriodInfo>Klicks geteilt durch Impressionen, aus den Summen der Auswahl berechnet. Hohe CTR allein belegt weder Reichweite noch qualifizierte Anfragen.</PeriodInfo></dt><dd>{pct(clicks,impressions)}</dd></div></dl>
 <SearchReadingGuide source={source}/>
 <section className="search-ranking"><div className="section-heading"><h2>Welche Begriffe tragen? <PeriodInfo>Ranking der gefilterten Berichtszeilen. Budget- und Klickanteile beziehen sich nur auf sichtbare Zeilen. SEO und Ads werden nicht addiert.</PeriodInfo></h2><label>Gewichtung<select value={metric} onChange={e=>setMetric(e.target.value)}><option value="clicks">Klicks</option><option value="impressions">Impressionen</option>{source!=='organic'&&<><option value="spend">Ausgaben</option><option value="conversions">Zielaktionen</option></>}</select></label></div>{top.map((r,i)=><div className="search-bar" key={i} tabIndex={0}><span>{r.term}<small>{r.campaign}</small></span><strong>{number(Number(r[metric as keyof Row]||0),metric==='spend'?r.currency:'count')}</strong><div><i style={{width:`${Number(r[metric as keyof Row]||0)/max*100}%`}}/></div><aside>{number(r.clicks)} Klicks · {number(r.impressions)} Einblendungen · {number(r.ctr)} % CTR<br/>{pct(r.clicks,clicks)} der sichtbaren Klicks{source!=='organic'&&` · ${pct(r.spend||0,spend)} der sichtbaren Ausgaben`}</aside></div>)}{!top.length&&<p>Keine Berichtszeilen für diese Auswahl.</p>}</section>
 <h2>Begriffe im Detail.</h2><p className="search-note">{Math.min(limit,sorted.length)} von {sorted.length} Berichtszeilen · nach der gewählten Gewichtung sortiert</p><div className="search-table"><table><thead><tr><th>Suchbegriff / Keyword</th><th>Klicks <PeriodInfo label="Klicks einordnen">Ein Klick zeigt Interesse am Ergebnis, aber noch keinen erfolgreichen Besuch oder Auftrag. Zielseite und nachfolgende Aktionen mitprüfen.</PeriodInfo></th><th>CTR <PeriodInfo label="Klickrate einordnen">Anteil der Einblendungen, die zu einem Klick führen. Beispiel: 5 Klicks aus 100 Einblendungen ergeben 5 %. Bei wenigen Einblendungen ist eine hohe Rate wenig belastbar.</PeriodInfo></th><th>{source==='organic'?'Ø Position':'Ausgaben'} <PeriodInfo>{source==='organic'?'Durchschnittliche Position des obersten Sonio-Ergebnisses je Einblendung. Eine kleinere Zahl bedeutet eine höhere Platzierung; Gerät, Ort und Suchkontext können variieren.':'Kosten der sichtbaren Berichtszeile in der Kontowährung. Verdeckte Suchanfragen fehlen in dieser Aufstellung.'}</PeriodInfo></th><th>{source==='organic'?'Zielseiten':'Zielaktionen'} <PeriodInfo>{source==='organic'?'Bis zu drei von Google gemeldete Seiten je Suchbegriff, nach Klicks sortiert.':'Die im Ads-Konto eingerichteten Conversions. Dies können unterschiedliche Aktionen sein, nicht automatisch Leads oder Verkäufe. Attribution kann zu Dezimalwerten führen.'}</PeriodInfo></th></tr></thead><tbody>{sorted.slice(0,limit).map((r,i)=><tr key={i}><td><b>{r.term}</b><small>{searchTopics.find(t=>t.id===searchTopic(r.term))?.label}</small><small>{r.campaign} {r.type} {r.match}</small></td><td>{number(r.clicks)}<small>{pct(r.clicks,clicks)} der Auswahl</small></td><td>{number(r.ctr)} %</td><td>{source==='organic'?number(r.position):number(r.spend,r.currency)}</td><td>{source==='organic'?r.pages?.map(p=><a key={p.url} href={p.url} target="_blank" rel="noreferrer">{new URL(p.url).pathname}</a>):number(r.conversions)}</td></tr>)}</tbody></table></div>{sorted.length>limit&&<button onClick={()=>setLimit(n=>n+10)}>Weitere 10 anzeigen</button>}
 <h2>Potenziale zum Prüfen. <PeriodInfo>Transparente redaktionelle Filter, keine KI-Analyse: SEO mindestens 100 Impressionen und Ø Position 5–20; Ads Ausgaben ohne erfasste Zielaktionen. Keine automatische Budget- oder Keyword-Änderung.</PeriodInfo></h2><p className="search-note">Prüfansätze aus den sichtbaren Zahlen, keine gesicherten Ursachen. Zuerst Suchabsicht und Datenbasis prüfen, dann einen gezielten Test planen.</p><div className="search-potentials">{potential.map((r,i)=><article key={i}><small>{source==='organic'?'Content prüfen':'Ziel und Tracking prüfen'}</small><h3>{r.term}</h3><p>{source==='organic'?`${number(r.impressions)} Einblendungen bei Ø Position ${number(r.position)}. Suchabsicht, Titel und passende Zielseite prüfen. Kein garantiertes Rankingpotenzial.`:`${number(r.spend,r.currency)} Ausgaben ohne erfasste Zielaktion. Suchabsicht, Conversion-Ziel und mögliche Verzögerung prüfen; nicht automatisch ausschliessen.`}</p><div className="search-potential-action"><strong>Nächster Schritt</strong><p>{source==='organic'?'Passende Zielseite öffnen: Beantwortet sie die konkrete Suchfrage? Titel und Einstieg gezielt überarbeiten und die Entwicklung im nächsten vergleichbaren Zeitraum prüfen.':'Suchanfrage mit Angebot und Anzeige abgleichen. Funktioniert die Messung der gewünschten Aktion? Erst danach über Budget oder Ausschlüsse entscheiden.'}</p></div></article>)}</div>{!potential.length&&<p>Für die definierten Prüfkriterien liegen aktuell keine Kandidaten vor.</p>}<p className="search-note">Neue Keyword-Ideen mit Suchvolumen folgen nach Prüfung des Keyword-Planner-Zugriffs. Hier werden bereits beobachtete Begriffe eingeordnet, keine erfundenen Suchvolumina angezeigt.</p><small>Stand: {q.data?.updated_at&&new Date(q.data.updated_at).toLocaleString('de-CH',{timeZone:'Europe/Zurich'})}</small></>}
 <EditorialQuote portrait={asset('brand/portraits/albert-einstein-v1.png')} text="The important thing is not to stop questioning." author="Albert Einstein" role="Physiker und Nobelpreisträger" source="https://www.pbs.org/wgbh/nova/einstein/wisd-nf.html"/></div>
}

function SearchReadingGuide({source}:{source:string}) {
 const [active,setActive]=useState('visibility');
 const lessons=[
  {id:'visibility',title:'Sichtbarkeit',meaning:'Impressionen zeigen, wie oft Sonio zu einer Suche eingeblendet wurde. Das ist nicht das gesamte Suchvolumen des Marktes.',action:'Relevante Begriffe mit vielen Einblendungen auswählen. Prüfen, ob Angebot und Zielseite die dahinterstehende Frage beantworten.'},
  {id:'interest',title:'Interesse',meaning:'Klicks zeigen Reaktionen. Die CTR setzt diese ins Verhältnis zu den Einblendungen: 5 Klicks bei 100 Einblendungen sind 5 %.',action:source==='organic'?'Bei vielen Einblendungen und wenigen Klicks Position, Seitentitel und Beschreibung gemeinsam prüfen. Markenbegriffe und allgemeine Fachbegriffe getrennt betrachten.':'Bei vielen Einblendungen und wenigen Klicks Suchabsicht, Anzeigentext und Angebot abgleichen. Unterschiedliche Kampagnenziele nicht pauschal vergleichen.'},
  {id:'impact',title:source==='organic'?'Platzierung':'Ergebnis',meaning:source==='organic'?'Die durchschnittliche Position beschreibt die Platzierung in den Suchergebnissen. Kleiner ist weiter oben; sie variiert je Suche und ist kein festes Ranking.':'Zielaktionen sind die im Ads-Konto eingerichteten Conversions. Kosten ohne Zielaktion können auf ein Problem hinweisen, aber auch auf Messlücken oder verzögerte Abschlüsse.',action:source==='organic'?'Für passende Fachbegriffe Inhalt und interne Verlinkung prüfen. Ob die Besuche wertvoll sind, anschliessend in Analytics anhand der Zielseite untersuchen.':'Tracking und Qualität der Zielaktionen prüfen. Erst bei ausreichend Daten Kosten und Nutzen bewerten; nicht allein wegen null Conversions ausschliessen.'},
 ];
 const lesson=lessons.find(l=>l.id===active)!;
 return <section className="search-reading"><div><h2>Zahlen lesen. Entscheidungen vorbereiten.</h2><p>Was sagen die Kennzahlen – und was lässt sich damit anfangen?</p></div><div className="search-reading-tabs" role="group" aria-label="Kennzahlen verstehen">{lessons.map(l=><button key={l.id} aria-pressed={active===l.id} onClick={()=>setActive(l.id)}>{l.title}</button>)}</div><div className="search-reading-body" aria-live="polite"><div><h3>Das bedeutet es</h3><p>{lesson.meaning}</p></div><div><h3>Damit weiterarbeiten</h3><p>{lesson.action}</p></div></div><small>Einzelne Klicks und kleine Datenmengen vorsichtig bewerten. Die Hinweise sind Lesehilfen, keine automatisch bestätigten Handlungsempfehlungen.</small></section>;
}
