import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {api,monthName,number} from '../api';
import {readablePostTitle} from '../comparison';
type Video={id:string;platform:string;title:string;published_at:string;image_url?:string;metrics:Record<string,number>|null};
export function VideoYearChart({demo}:{demo:boolean}){
 const year=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Zurich',year:'numeric'}).format(new Date());
 const [period,setPeriod]=useState(''),[platform,setPlatform]=useState('');
 const q=useQuery({queryKey:['video-library'],queryFn:()=>api<{videos:Video[]}>('/videos/library'),enabled:!demo,staleTime:60000});
 const videos=(q.data?.videos||[]).filter(v=>v.published_at.startsWith(period||year)&&(!platform||v.platform===platform));
 const dates=[...new Set(videos.map(v=>v.published_at.slice(0,10)))].sort();
 const rows=dates.map(date=>{const posts=videos.filter(v=>v.published_at.startsWith(date));const total=(p:string)=>{const values=posts.filter(v=>v.platform===p).map(v=>v.metrics?.[p==='youtube'?'views':'video_views']).filter(v=>v!=null) as number[];return values.length?values.reduce((a,b)=>a+b,0):null};return {date,linkedin:total('linkedin'),youtube:total('youtube')}});
 return <section className="panel video-overview-chart"><div className="section-heading"><div><h2>Video Performance {year}</h2><p>{videos.length} veröffentlichte Videos · Aufrufe seit Veröffentlichung</p></div><label>Zeitraum<select aria-label="Diagramm-Zeitraum" value={period} onChange={e=>setPeriod(e.target.value)}><option value="">Ganzes Jahr {year}</option>{Array.from({length:12},(_,i)=>`${year}-${String(i+1).padStart(2,'0')}`).map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select></label><label>Plattform<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="">LinkedIn & YouTube</option><option value="linkedin">LinkedIn</option><option value="youtube">YouTube</option></select></label></div><p className="video-method-note">Nach Veröffentlichungstag eingeordnet. Punkte zeigen den verfügbaren Gesamtstand der an diesem Tag veröffentlichten Videos, keine täglichen Aufrufe. LinkedIn und YouTube zählen Aufrufe unterschiedlich. Nicht verfügbare Kennzahlen bleiben leer.</p>
 {demo?<p>Videodaten sind in der öffentlichen Demo nicht verfügbar.</p>:q.isPending?<p role="status">Videos werden geladen…</p>:q.isError?<p role="alert">Videodaten konnten nicht geladen werden. <button onClick={()=>q.refetch()}>Erneut versuchen</button></p>:!videos.length?<p>Keine importierten Videos für diese Auswahl.</p>:<><div className="video-chart-legend"><span style={{color:'#1268cf'}}>LinkedIn</span><span style={{color:'#a44b19'}}>YouTube</span></div><ResponsiveContainer width="100%" height={340}><LineChart data={rows} margin={{left:0,right:24,top:20,bottom:15}}><CartesianGrid vertical={false} stroke="#d9e4ef"/><XAxis dataKey="date" minTickGap={32} tickFormatter={v=>new Date(v+'T12:00:00').toLocaleDateString('de-CH',{day:'numeric',month:'short'})}/><YAxis/><Tooltip content={({active,label})=>active?<div className="video-hover"><strong>{String(label)}</strong>{videos.filter(v=>v.published_at.startsWith(String(label))).map(v=><article key={v.platform+v.id}>{v.image_url&&<img src={v.image_url} alt=""/>}<div><b>{readablePostTitle(v.title)}</b><p>{v.platform==='youtube'?'YouTube':'LinkedIn'} · {number(v.metrics?.[v.platform==='youtube'?'views':'video_views'])} Aufrufe</p></div></article>)}</div>:null}/>{(!platform||platform==='linkedin')&&<Line type="linear" dataKey="linkedin" name="LinkedIn" stroke="#1268cf" strokeWidth={2} dot={{r:4}} connectNulls/>}{(!platform||platform==='youtube')&&<Line type="linear" dataKey="youtube" name="YouTube" stroke="#a44b19" strokeWidth={2} dot={{r:4}} connectNulls/>}</LineChart></ResponsiveContainer></>}
 </section>;
}
