import {Play} from 'lucide-react';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api,number,monthName} from '../api';
import {ChannelIcon} from './ui';
import {averageWatchSeconds,readablePostTitle} from '../comparison';
type Video={id:string;platform:string;title:string;text?:string;published_at:string;image_url?:string;metrics:Record<string,number>|null};
type Library={videos:Video[];playlists:{id:string;title:string;video_ids:string[]}[]};
export function VideoLibrary({demo,linkedinOnly=false}:{demo:boolean;linkedinOnly?:boolean}){
 const q=useQuery({queryKey:['video-library'],queryFn:()=>api<Library>('/videos/library'),enabled:!demo,staleTime:60000});
 const [playing,setPlaying]=useState(false);
 const [platform,setPlatform]=useState(linkedinOnly?'linkedin':''),[period,setPeriod]=useState(''),[playlist,setPlaylist]=useState(''),[selected,setSelected]=useState(''),[search,setSearch]=useState('');
 const all=(q.data?.videos||[]).filter(v=>!linkedinOnly||v.platform==='linkedin');
 const months=[...new Set(all.map(v=>v.published_at.slice(0,7)))].sort().reverse();
 const filtered=all.filter(v=>(!platform||v.platform===platform)&&(!period||v.published_at.startsWith(period))&&(!playlist||(v.platform==='youtube'&&q.data?.playlists.find(p=>p.id===playlist)?.video_ids.includes(v.id)))&&(!search||`${v.title} ${v.text||''}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())));
 const hasSelection=Boolean(selected||playlist||period||search);
 const list=hasSelection?filtered.filter(v=>!selected||`${v.platform}:${v.id}`===selected):[];
 const lead=all[0];
 const reset=()=>setSelected('');
 return <section className="all-video-library">{lead&&<div className="video-lead"><h2>Das aktuelle Leitvideo</h2>{!playing?<button className="video-lead-poster" aria-label={`Video abspielen: ${readablePostTitle(lead.title)}`} onClick={()=>setPlaying(true)}>{lead.image_url?<img src={lead.image_url} alt={readablePostTitle(lead.title)}/>:<span>{readablePostTitle(lead.title)}</span>}<span className="video-lead-play"><Play size={30} fill="currentColor"/>Video abspielen</span></button>:lead.platform==='youtube'?<iframe title={readablePostTitle(lead.title)} src={`https://www.youtube-nocookie.com/embed/${encodeURIComponent(lead.id)}`} allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen/>:<iframe title={readablePostTitle(lead.title)} src={`https://www.linkedin.com/embed/feed/update/${encodeURIComponent(lead.id)}`} allow="autoplay; fullscreen" allowFullScreen/>}<h3>{readablePostTitle(lead.title)}</h3><p>Veröffentlicht am {new Date(lead.published_at).toLocaleDateString('de-CH')} auf {lead.platform==='youtube'?'YouTube':'LinkedIn'}. Wiedergabe per Klick.</p></div>}<div className="section-heading"><div><h2>{linkedinOnly?'Alle LinkedIn-Videos':'Alle Videos'}</h2><p>{linkedinOnly?'LinkedIn':'LinkedIn und YouTube'} · {filtered.length} Videos für diese Auswahl</p></div></div>
 <div className="video-library-filters"><label>Plattform<select disabled={linkedinOnly} value={platform} onChange={e=>{setPlatform(e.target.value);setPlaylist('');reset()}}><option value="">Beide Plattformen</option><option value="linkedin">LinkedIn</option><option value="youtube">YouTube</option></select></label><label>Veröffentlichung<select value={period} onChange={e=>{setPeriod(e.target.value);reset()}}><option value="">Alle Monate</option>{months.map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select></label><label>Playlist<select disabled={linkedinOnly} value={playlist} onChange={e=>{setPlaylist(e.target.value);if(e.target.value)setPlatform('youtube');reset()}}><option value="">Alle Playlists</option>{q.data?.playlists.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Video auswählen<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Alle Videos</option>{filtered.map(v=><option key={`${v.platform}:${v.id}`} value={`${v.platform}:${v.id}`}>{v.platform==='youtube'?'YouTube':'LinkedIn'} · {readablePostTitle(v.title)}</option>)}</select></label><label>Titel suchen<input type="search" value={search} onChange={e=>{setSearch(e.target.value);reset()}} placeholder="Video oder Thema"/></label></div>
 <p className="video-method-note">Alle bisher importierten Videos, neueste zuerst. Kennzahlen zeigen den letzten verfügbaren Gesamtstand seit Veröffentlichung. Fehlende Werte bleiben «—».</p>
 {demo?<p>Die öffentliche Demo enthält keine echten Videos.</p>:q.isPending?<p role="status">Videobibliothek wird geladen…</p>:q.isError?<p role="alert">Videos konnten nicht geladen werden. <button onClick={()=>q.refetch()}>Erneut versuchen</button></p>:<div className="video-library-grid">{list.map(v=>{const yt=v.platform==='youtube',m=v.metrics||{};const stats=[['Aufrufe',yt?m.views:m.video_views],['Ø Betrachtungsdauer (Sek.)',yt?m.averageViewDuration:averageWatchSeconds(m)],['Likes',m.likes],['Kommentare',m.comments],['Geteilt',m.shares]] as const;return <article className="video-library-item" key={`${v.platform}:${v.id}`}><button className="video-library-preview" aria-label={`Details: ${readablePostTitle(v.title)}`} aria-expanded={selected===`${v.platform}:${v.id}`} onClick={()=>setSelected(selected===`${v.platform}:${v.id}`?'':`${v.platform}:${v.id}`)}>{v.image_url?<img loading="lazy" src={v.image_url} alt={readablePostTitle(v.title)}/>:<span>Keine Videovorschau</span>}<span className="video-library-overlay"><strong>{readablePostTitle(v.title)}</strong><span>{number(yt?m.views:m.video_views)} Aufrufe</span><span>Ø {number(yt?m.averageViewDuration:averageWatchSeconds(m))} Sekunden</span></span></button><div className="video-library-body"><div className="video-library-meta"><ChannelIcon id={yt?'youtube':'linkedin_organic'} size={24}/><span>{yt?'YouTube':'LinkedIn'}</span><time>{new Date(v.published_at).toLocaleDateString('de-CH')}</time></div><h3>{readablePostTitle(v.title)}</h3><dl>{stats.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{number(value)}</dd></div>)}</dl>{selected&&v.text&&<p>{v.text}</p>}</div></article>})}</div>}{!q.isPending&&!q.isError&&!demo&&hasSelection&&!list.length&&<p>Keine Videos für diese Auswahl. Filter anpassen, um weitere Videos zu sehen.</p>}{!hasSelection&&<p>Playlist, Monat oder einzelnes Video auswählen, um weitere Videos anzuzeigen.</p>}</section>
}
