import {RecommendationTeaser} from "./RecommendationTeaser";
import {useState,type ReactNode} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api,number,monthName} from '../api';
import {averageWatchSeconds,readablePostTitle} from '../comparison';
import {ChannelIcon} from './ui';
import {EditorialQuote} from './EditorialQuote';
import {VideoYearChart} from './VideoYearChart';
import {asset} from '../staticDemo';
import '../video-insights.css';
type Video={id:string;platform:string;title:string;published_at:string;image_url?:string;updated_at?:string;metrics:Record<string,number>|null};
type Library={videos:Video[];playlists:{id:string;title:string;video_ids:string[]}[]};
const views=(v:Video)=>v.metrics?.[v.platform==='youtube'?'views':'video_views'];
const watch=(v:Video)=>v.platform==='youtube'?v.metrics?.averageViewDuration:averageWatchSeconds(v.metrics||{});
export function VideoInsightsHero(){return <><div className="marketing-mast"><h1>Video Insights.</h1></div><section className="marketing-hero"><img src={asset('brand/sonio-blog-header.jpg')} alt="Sonio Berglandschaft mit Fahrer und Zielflagge"/><div><h2>Gute Geschichten wirken weiter.</h2><p>Inhalte verbinden. Potenziale entdecken. Mehr aus Video machen.</p></div></section><p className="directory-intro">Ein Blick auf das Videoportfolio von LinkedIn und YouTube: Inhalte gezielt gegenüberstellen, Themen entdecken und nächste Schritte für die Vermarktung planen. Die Detailauswertung bleibt im jeweiligen Kanal.</p></>}
export function VideoInsights({demo,onChannel,actions}:{demo:boolean;onChannel:(channel:string)=>void;actions?:ReactNode}){
 const q=useQuery({queryKey:['video-library'],queryFn:()=>api<Library>('/videos/library'),enabled:!demo,staleTime:60000});
 const current=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Zurich',year:'numeric',month:'2-digit'}).format(new Date());
 const [period,setPeriod]=useState(current.slice(0,4)),[topic,setTopic]=useState(''),[li,setLi]=useState(''),[yt,setYt]=useState('');
 const all=q.data?.videos||[];
 const date=(v:Video)=>new Date(v.published_at).toLocaleDateString('sv-SE',{timeZone:'Europe/Zurich'});
 const list=all.filter(v=>date(v).startsWith(period));
 const chosen=(platform:string,id:string)=>list.find(v=>v.platform===platform&&v.id===id)||list.find(v=>v.platform===platform);
 const years=[...new Set([current.slice(0,4),...all.map(v=>date(v).slice(0,4))])].sort().reverse();
 const topicVideos=topic?list.filter(v=>v.platform==='youtube'&&q.data?.playlists.find(p=>p.id===topic)?.video_ids.includes(v.id)):[];
 const candidate=[...topicVideos].filter(v=>views(v)!=null).sort((a,b)=>views(b)!-views(a)!)[0];
 return <div className="vi-workspace"><div className="vi-actions">{actions}</div><div className="section-heading"><div><h2>Ein Portfolio. Zwei Perspektiven.</h2><p>Veröffentlichungen im ausgewählten Zeitraum · verfügbarer Gesamtstand je Video</p></div><label>Veröffentlichungszeitraum<select value={period} onChange={e=>{setPeriod(e.target.value);setLi('');setYt('')}}>{years.map(y=><option key={y} value={y}>Ganzes Jahr {y}</option>)}{Array.from({length:12},(_,i)=>{const d=new Date(current+'-01T12:00:00');d.setMonth(d.getMonth()-i);const m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;return <option value={m} key={m}>{monthName(m)}</option>})}</select></label></div>
 {demo?<p>Diese Variante zeigt keine echten Videodaten in der öffentlichen Demo.</p>:q.isPending?<p role="status">Videoportfolio wird geladen…</p>:q.isError?<p role="alert">Das Portfolio konnte nicht geladen werden. <button onClick={()=>q.refetch()}>Erneut versuchen</button></p>:<>
 <div className="vi-platforms">{['linkedin','youtube'].map(platform=>{const items=list.filter(v=>v.platform===platform);const available=items.filter(v=>views(v)!=null);return <article key={platform}><div className="vi-channel"><ChannelIcon id={platform==='youtube'?'youtube':'linkedin_organic'} size={40}/><h3>{platform==='youtube'?'YouTube':'LinkedIn'}</h3></div><dl><div><dt>Importierte Videos</dt><dd>{number(items.length)}</dd></div><div><dt>Erfasste Aufrufe</dt><dd>{available.length?number(available.reduce((sum,v)=>sum+views(v)!,0)):'—'}</dd></div></dl><p>{available.length} von {items.length} Videos mit Aufrufzahlen. Keine gemeinsame Reichweitensumme beider Kanäle.</p><button className="text-button" onClick={()=>onChannel(platform==='youtube'?'youtube':'linkedin_organic')}>Zur Kanalauswertung →</button></article>})}</div>
 <section className="vi-pair"><h2>Ein Inhalt, zwei Bühnen.</h2><p>Passende Veröffentlichungen selbst auswählen. Die Vorauswahl zeigt das neueste importierte Video je Kanal und stellt keine bestätigte Inhaltszuordnung dar.</p><div className="vi-pair-grid">{['linkedin','youtube'].map(platform=>{const v=chosen(platform,platform==='linkedin'?li:yt);return <article key={platform}><label>{platform==='youtube'?'YouTube':'LinkedIn'}-Video<select value={v?.id||''} onChange={e=>platform==='linkedin'?setLi(e.target.value):setYt(e.target.value)}><option value="" disabled>Video auswählen</option>{list.filter(x=>x.platform===platform).map(x=><option key={x.id} value={x.id}>{readablePostTitle(x.title)}</option>)}</select></label>{v?<><a className="vi-preview" href={platform==='youtube'?`https://www.youtube.com/watch?v=${v.id}`:`https://www.linkedin.com/feed/update/${encodeURIComponent(v.id)}/`} target="_blank" rel="noreferrer">{v.image_url?<img src={v.image_url} alt={readablePostTitle(v.title)}/>:<span>Kein Vorschaubild verfügbar</span>}<span className="vi-preview-overlay">Video auf {platform==='youtube'?'YouTube':'LinkedIn'} ansehen</span></a><h3>{readablePostTitle(v.title)}</h3><p>{new Date(v.published_at).toLocaleDateString('de-CH')} · Stand {v.updated_at?new Date(v.updated_at).toLocaleDateString('de-CH'):'nicht verfügbar'}</p><dl><div><dt>Aufrufe</dt><dd>{number(views(v))}</dd></div><div><dt>Ø Betrachtungsdauer</dt><dd>{number(watch(v))} Sek.</dd></div></dl></>:<p>Kein importiertes Video für diese Auswahl.</p>}</article>})}</div><p className="vi-note">LinkedIn und YouTube zählen Aufrufe unterschiedlich. Videolänge, Veröffentlichungsalter und Werbeunterstützung berücksichtigen; diese Werte ergeben keine kanalübergreifende Rangliste.</p></section>
 <section className="vi-topics"><h2>Themen mit Anschluss.</h2><p>YouTube-Playlists strukturieren das Portfolio. Für LinkedIn besteht noch keine verifizierte Themenzuordnung.</p><div className="vi-topic-buttons" role="group" aria-label="Videothemen">{q.data?.playlists.map(p=><button key={p.id} aria-pressed={topic===p.id} onClick={()=>setTopic(topic===p.id?'':p.id)}>{p.title==='EVENTS'?'Events':p.title==='ARCHIV'?'Archiv':p.title}<span>{list.filter(v=>v.platform==='youtube'&&p.video_ids.includes(v.id)).length}</span></button>)}</div>{topic&&<div className="vi-topic-detail">{candidate?<><h3>Ein Ausgangspunkt: {readablePostTitle(candidate.title)}</h3><p>{number(views(candidate))} Aufrufe · höchster verfügbarer Aufrufstand in dieser Playlist und Auswahl. Vor einer Weiterverwendung Aktualität, Videolänge und Werbeanteil prüfen.</p><button className="text-button" onClick={()=>{setYt(candidate.id)}}>Für die Gegenüberstellung auswählen</button></>:<p>Für dieses Thema liegen im ausgewählten Zeitraum keine Videoaufrufe vor.</p>}</div>}</section>
 </>}
 <VideoYearChart demo={demo}/>
 <section className="vi-decisions"><h2>Was aus einem Video werden kann.</h2><p>Redaktionelle Prüffragen für die nächste Marketingrunde – keine automatisch erstellte KI-Analyse.</p><div><article><h3>Eine starke Szene. Ein neuer Einstieg.</h3><p>Bei einem relevanten Fachvideo prüfen, ob eine prägnante Antwort als kurzer LinkedIn-Ausschnitt funktioniert. Zum vollständigen Video verlinken.</p></article><article><h3>Ein Thema. Mehrere Kontaktpunkte.</h3><p>Testimonial, Fachbeitrag und passendes Mailing gemeinsam planen. Die manuelle Gegenüberstellung hilft, vorhandene Inhalte wiederzufinden.</p></article><article><h3>Aufmerksamkeit gezielt verlängern.</h3><p>Vor zusätzlicher Bewerbung Betrachtungsdauer und Aktualität prüfen. Bezahlte Aufrufe sind im YouTube-Kanal separat ausgewiesen; Budgetempfehlungen benötigen verifizierte Kostendaten.</p></article></div></section>
 <RecommendationTeaser/><EditorialQuote text="Life is a tragedy when seen in close-up, but a comedy in long-shot." author="Charlie Chaplin" role="Schauspieler und Regisseur" source="https://www.charliechaplin.com/en/quotes/11"/>
 </div>;
}
