import {MetricHelp} from './MetricHelp';
import {RecommendationTeaser} from "./RecommendationTeaser";
import { EditorialQuote } from './EditorialQuote';
import '../youtube-cockpit.css';
import { Play, ExternalLink, RefreshCw } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import { asset } from '../staticDemo';
import { PeriodInfo } from "./PeriodInfo";
import { useState, type ReactNode } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api, number, monthName } from '../api';
type Video={id:string;title:string;published_at:string;image_url:string|null;duration?:string;lifetime?:Record<string,number>;metrics:Record<string,number|null>|null};
type Library={available_years?:number[];latest_video?:Video|null;videos:Video[];playlists:{id:string;title:string;video_ids:string[]}[];start:string;end:string;updated_at:string;warning?:string};
const playlistOrder = ['Sonio.onPoint','Testimonial','Full Service Provider','Events','Image','Sonio Vodcasts','Partner','Archiv'];
const playlistName = (title:string) => playlistOrder.find(name=>name.toLocaleLowerCase()===title.trim().toLocaleLowerCase()) || title;
const playlistRank = (title:string) => {const index=playlistOrder.indexOf(playlistName(title));return index<0?playlistOrder.length-1.5:index};
const labels:Record<string,string>={YT_OTHER_PAGE:'Weitere YouTube-Seiten',YT_SEARCH:'YouTube-Suche',RELATED_VIDEO:'Empfohlene Videos',EXT_URL:'Externe Websites',NO_LINK_OTHER:'Direkt oder unbekannt',SUBSCRIBER:'Startseite & Abos',ADVERTISING:'Werbung',PLAYLIST:'Playlists',YT_CHANNEL:'Kanalseiten',END_SCREEN:'Abspann',NOTIFICATION:'Benachrichtigungen',SHORTS:'Shorts-Feed'};
const kpis:Record<string,string>={views:'Aufrufe',estimatedMinutesWatched:'Wiedergabezeit (Min.)',averageViewDuration:'Ø Betrachtungsdauer',averageViewPercentage:'Ø angesehen (%)',likes:'Likes',comments:'Kommentare',shares:'Geteilt'};
const explanations:Record<string,string>={
views:'Aufrufe zeigt, wie oft YouTube das Video seit Veröffentlichung gezählt hat. Das ist keine Anzahl eindeutiger Personen: Wiederholte Aufrufe können enthalten sein. Nutze die Kennzahl für Reichweite und gemeinsam mit der Betrachtungsdauer für die Nutzung. Werbung kann enthalten sein; die Zugriffsquellen helfen bei der Einordnung.',
estimatedMinutesWatched:'Wiedergabezeit ist die von YouTube geschätzte gesamte Betrachtungszeit seit Veröffentlichung, angegeben in Minuten. Sie verbindet Aufrufmenge und Sehdauer. Viele Minuten können durch viele kurze oder wenige lange Aufrufe entstehen. Vergleiche deshalb auch Aufrufe, Videolänge und durchschnittliche Betrachtungsdauer. YouTube liefert gerundete Minuten; 0 Minuten muss nicht bedeuten, dass niemand kurz zugesehen hat.',
averageViewDuration:'Die durchschnittliche Betrachtungsdauer zeigt, wie viele Sekunden ein Video pro berücksichtigtem Aufruf angesehen wurde. YouTube berechnet diesen Durchschnitt. Setze ihn zur Videolänge ins Verhältnis: 30 Sekunden sind bei einem kurzen Testimonial anders zu bewerten als bei einem zehnminütigen Interview. Ohne Aufrufe ist kein sinnvoller Durchschnitt möglich; dann steht hier «—».',
averageViewPercentage:'Dieser Wert beschreibt, welcher Anteil der Videolänge durchschnittlich angesehen wurde. 50 % bedeutet ungefähr die halbe Videolänge pro berücksichtigtem Aufruf, nicht dass die Hälfte aller Zuschauer bis zum Ende blieb. Wiederholungen können Werte über 100 % erzeugen. Vergleiche möglichst ähnliche Formate und Längen; bei sehr wenigen Aufrufen schwankt der Wert stark.',
likes:'Likes zeigt den aktuellen Bestand positiver Bewertungen am Video laut YouTube. Sie zeigen aktive Zustimmung, aber nicht die Meinung aller Zuschauer. Vergleiche sie im Verhältnis zu Aufrufen und bei ähnlichen Inhalten. Die Zahl zeigt den aktuellen Like-Bestand am Video.',
comments:'Kommentare zeigt den aktuellen Kommentarbestand am Video laut YouTube. Sie zeigen Gesprächsaktivität, keine automatisch positive Resonanz und keine eindeutige Personenzahl. Für eine Bewertung ist zusätzlich der Inhalt der Kommentare relevant. Die Zahl zeigt den aktuellen Kommentarbestand am Video.',
shares:'Geteilt zählt die von YouTube erfassten Teilungen seit Veröffentlichung, etwa über die Teilen-Funktion. Manuell kopierte Links oder Weiterleitungen ausserhalb der erfassten Funktionen sind nicht vollständig abgedeckt. Teilungen zeigen Weiterempfehlung, belegen aber weder zusätzliche Aufrufe noch Website-Conversions.'};
function durationLabel(value?:string){const m=value?.match(/^P(?:(\d+)D)?T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/);if(!m)return '—';const seconds=Number(m[1]||0)*86400+Number(m[2]||0)*3600+Number(m[3]||0)*60+Number(m[4]||0);return seconds>=3600?`${Math.floor(seconds/3600)}:${String(Math.floor(seconds/60)%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`:`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
function Sources({id,month,year}:{id:string;month:string;year:boolean}) {
 const q=useQuery({queryKey:['youtube-lifetime-traffic',id,month,year],queryFn:()=>api<{sources:{source:string;views:number;watch_minutes:number}[]}>(`/youtube/videos/${id}/traffic?month=${month}&year=${year}`),staleTime:3600000});
 return <div className="yt-sources">{q.isPending?<p role="status">Zugriffsquellen werden geladen…</p>:q.isError?<p role="alert">Zugriffsquellen konnten nicht geladen werden. <button onClick={()=>q.refetch()}>Erneut versuchen</button></p>:<><p>YouTube ordnet Aufrufe diesen Quellen zu. Externe Websites sind zusammengefasst; einzelne Personen werden nicht angezeigt.</p>{q.data?.sources.length?<dl>{q.data.sources.map(s=><div key={s.source}><dt>{labels[s.source]||s.source}</dt><dd>{number(s.views)} Aufrufe · {number(s.watch_minutes)} Min.</dd></div>)}</dl>:<p>Für diesen Zeitraum liefert YouTube keine Zugriffsquellen.</p>}</>}</div>;
}
export function YouTubeHero() {
 return <><div className="li-mast"><div><h1>YouTube Cockpit.</h1></div><span>Marketing · Video</span></div><section className="li-hero"><img src={asset('brand/sonio-blog-header.jpg')} alt="Sonio Berglandschaft mit Fahrer und Zielflagge"/><div><h2>Geschichten zeigen. Aufmerksamkeit gewinnen.</h2><p>Welche Videos Menschen erreichen – und ihr Interesse halten.</p></div></section><p className="yt-pitch">Videos machen Sonio erlebbar. Dieses Cockpit zeigt, welche Inhalte Aufmerksamkeit gewinnen, wie lange sie halten und über welche Wege das Publikum zu ihnen findet.</p></>;
}
const primary = ['views','estimatedMinutesWatched','averageViewPercentage','averageViewDuration'];
const dateLabel = (s:string) => new Date(s).toLocaleDateString('de-CH',{timeZone:'Europe/Zurich'});
function metric(v:Video,key:string) {
 const n=v.metrics?.[key]; if(n == null || !Number.isFinite(n))return '—';
 if(key==='averageViewDuration')return `${Math.floor(Math.round(n)/60)}:${String(Math.round(n)%60).padStart(2,'0')} Min.`;
 return `${number(n)}${key==='averageViewPercentage'?' %':key==='estimatedMinutesWatched'?' Min.':''}`;
}
function Poster({v}:{v:Video}) {
 const [playing,setPlaying]=useState(false);
 return <div className="yt-feature-media" style={v.image_url?{backgroundImage:`url(${v.image_url})`,backgroundSize:"cover",backgroundPosition:"center",backgroundRepeat:"no-repeat"}:undefined}>{playing?<><iframe title={v.title} src={`https://www.youtube-nocookie.com/embed/${encodeURIComponent(v.id)}?autoplay=1`} allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen/><button className="yt-player-back" onClick={()=>setPlaying(false)}>Vorschaubild anzeigen</button></>:<button onClick={()=>setPlaying(true)} aria-label={`Video abspielen: ${v.title}`}>{v.image_url?<img src={v.image_url} alt={v.title}/>:<span>{v.title}</span>}<span className="yt-play"><Play size={30} fill="currentColor"/>Video abspielen</span></button>}</div>;
}
export function YouTubeVideos({demo,actions,initialMonth}:{demo:boolean;actions?:ReactNode;initialMonth?:string}) {
 const current=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Zurich',year:'numeric',month:'2-digit'}).format(new Date());
 const [month,setMonth]=useState(initialMonth||current),[year,setYear]=useState(false),[playlist,setPlaylist]=useState(''),[video,setVideo]=useState(''),[explain,setExplain]=useState('views'),[expanded,setExpanded]=useState(false),[chartKey,setChartKey]=useState('views');
 const endpoint=`/youtube/videos?month=${month}&year=${year}`;
 const q=useQuery({queryKey:['youtube-published-videos',month,year],queryFn:()=>api<Library>(endpoint),enabled:!demo,staleTime:3600000});
 const latest=useQuery({queryKey:['youtube-published-videos',current,false],queryFn:()=>api<Library>(`/youtube/videos?month=${current}`),enabled:!demo,staleTime:3600000});
 const [refreshing,setRefreshing]=useState(false),[refreshError,setRefreshError]=useState(false);
 const list=q.data?.videos.filter(v=>(!playlist||q.data?.playlists.find(p=>p.id===playlist)?.video_ids.includes(v.id))&&(!video||v.id===video))||[];
 const chart=[...list].sort((a,b)=>a.published_at.localeCompare(b.published_at)).map(v=>({...v,value:v.metrics?.[chartKey]??null}));
 const lead=latest.data?.latest_video;
 const reset=()=>{setVideo('');setExpanded(false)};
 const refresh=async()=>{setRefreshing(true);setRefreshError(false);try{await api(endpoint+'&refresh=true');await q.refetch();if(month!==current||year){await api(`/youtube/videos?month=${current}&refresh=true`);await latest.refetch()}}catch{setRefreshError(true)}finally{setRefreshing(false)}};
 const sum=(key:string)=>list.length&&list.every(v=>v.metrics?.[key]!=null)?number(list.reduce((n,v)=>n+v.metrics![key]!,0)):'—';
 return <section className="yt-cockpit">
 <div className="section-heading"><h2>Im Fokus.</h2>{actions}</div>
 {demo?<p>Videodetails sind in der öffentlichen Demo nicht verfügbar.</p>:lead?<section className="yt-feature"><Poster key={lead.id} v={lead}/><div><h3>{lead.title}</h3><p>Das neueste Video von Sonio</p><p>{dateLabel(lead.published_at)} · Länge {durationLabel(lead.duration)}</p><a href={`https://www.youtube.com/watch?v=${lead.id}`} target="_blank" rel="noreferrer">Auf YouTube ansehen <ExternalLink size={14}/></a>{latest.data?.warning&&<p role="status">{latest.data.warning}</p>}</div></section>:<p role="status">{latest.isPending?'Das aktuelle Video wird geladen…':'Das aktuelle Video ist derzeit nicht verfügbar.'}{latest.isError&&<button className="text-button" onClick={()=>latest.refetch()}>Erneut versuchen</button>}</p>}
 <div className="section-heading yt-section-title"><h2>Aufmerksamkeit &amp; Wirkung.</h2><span>{year?month.slice(0,4):monthName(month)} <PeriodInfo>Auswahl nach Veröffentlichungsdatum. Die Kennzahlen zeigen den verfügbaren Gesamtstand seit Veröffentlichung, keine Monatsleistung. Datenstand: {q.data?.updated_at?new Date(q.data.updated_at).toLocaleString('de-CH'):'—'}. Fehlend ist nicht null. Durchschnittswerte unterschiedlicher Videos werden nicht pauschal gemittelt.</PeriodInfo></span></div>
 <div className="yt-controls"><label>Veröffentlichungszeitraum<select aria-label="Veröffentlichungszeitraum" value={year?`year:${month.slice(0,4)}`:month} onChange={e=>{const isYear=e.target.value.startsWith('year:');setYear(isYear);setMonth(isYear?e.target.value.slice(5)+'-01':e.target.value);reset()}}>{Array.from({length:12},(_,i)=>{const d=new Date(current+'-01T12:00:00');d.setMonth(d.getMonth()-i);const m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;return <option key={m} value={m}>{monthName(m)}</option>})}{(latest.data?.available_years||q.data?.available_years||[Number(current.slice(0,4))]).map(y=><option key={y} value={`year:${y}`}>Ganzes Jahr {y}</option>)}</select></label><label>Video<select aria-label="Video" value={video} onChange={e=>{setVideo(e.target.value);setExpanded(false)}}><option value="">Alle Videos</option>{q.data?.videos.filter(v=>!playlist||q.data?.playlists.find(p=>p.id===playlist)?.video_ids.includes(v.id)).map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label><button className="text-button" disabled={demo||refreshing||q.isPending} onClick={refresh}><RefreshCw size={16}/>{refreshing?'Wird aktualisiert…':'Videoauswahl aktualisieren'}</button></div>
 {(q.data?.warning||refreshError)&&<p role="alert">{q.data?.warning||'Aktualisierung fehlgeschlagen. Der letzte Stand bleibt sichtbar.'}</p>}
 {!demo&&(q.isPending?<p role="status">Videos und Kennzahlen werden geladen…</p>:q.isError?<p role="alert">Videos konnten nicht geladen werden. <button onClick={()=>q.refetch()}>Erneut versuchen</button></p>:<>
 <div className="yt-overview"><div><span>Videos in der Auswahl</span><strong>{number(list.length)}</strong></div><div><span>Aufrufe gesamt</span><strong>{sum('views')}</strong></div><div><span>Wiedergabezeit gesamt</span><strong>{sum('estimatedMinutesWatched')} <small>Min.</small></strong></div></div>
 <section className="yt-chart"><div className="section-heading"><div><h3>Videos im Vergleich. <PeriodInfo label="Videovergleich erklärt">Die Auswahl filtert die Veröffentlichung; jeder Punkt zeigt den verfügbaren Gesamtstand des Videos. Videoalter, Länge und Werbeunterstützung beeinflussen die Zahlen. Die Linie verbindet Videos und ist kein Verlauf ihrer täglichen Aufrufe.</PeriodInfo></h3><p>Veröffentlichungen mit aktuellem Gesamtstand. Ältere Videos hatten mehr Zeit, Aufrufe zu sammeln.</p></div><label>Kennzahl<select value={chartKey} onChange={e=>setChartKey(e.target.value)}>{primary.map(k=><option key={k} value={k}>{kpis[k]}</option>)}</select></label></div>{chart.length?<ResponsiveContainer width="100%" height={280}><LineChart data={chart} margin={{top:20,right:20,left:0,bottom:10}} accessibilityLayer><CartesianGrid vertical={false} stroke="#dce9f4"/><XAxis dataKey="id" tickFormatter={id=>dateLabel(chart.find(v=>v.id===id)!.published_at)} tick={{fontSize:12}} minTickGap={36}/><YAxis tick={{fontSize:12}} width={62}/><Tooltip content={({active,payload})=>{const v=payload?.[0]?.payload as Video|undefined;return active&&v?<div className="yt-chart-tooltip">{v.image_url&&<img src={v.image_url} alt=""/>}<strong>{v.title}</strong><span>{dateLabel(v.published_at)}</span>{primary.map(k=><div key={k}><span>{kpis[k]}</span><b>{metric(v,k)}</b></div>)}</div>:null}}/><Line dataKey="value" name={kpis[chartKey]} stroke="#0075d9" strokeWidth={3} dot={{r:4}} activeDot={{r:7}} connectNulls={false}/></LineChart></ResponsiveContainer>:<p>Keine Videos für diese Auswahl vorhanden.</p>}</section>
 <div className="yt-playlist-picker" role="group" aria-label="Playlists"><span>Playlists entdecken</span><div><button type="button" aria-pressed={!playlist} onClick={()=>{setPlaylist('');reset()}}>Alle</button>{q.data?.playlists.slice().sort((a,b)=>playlistRank(a.title)-playlistRank(b.title)).map(p=><button type="button" key={p.id} aria-pressed={playlist===p.id} onClick={()=>{setPlaylist(p.id);reset()}}>{playlistName(p.title)}</button>)}</div></div>
 <div className="section-heading yt-section-title"><h2>Inhalte, die bewegen.</h2><span>{list.length} Videos</span></div>
 <MetricHelp label="Videokennzahlen erklärt" entries={Object.entries(kpis).map(([key,label])=>({key,label,text:explanations[key]}))}/><div className="yt-editorial-list">{(expanded?list:list.slice(0,5)).map(v=><article key={v.id} className="yt-editorial-video"><a className="yt-thumbnail" href={`https://www.youtube.com/watch?v=${v.id}`} target="_blank" rel="noreferrer">{v.image_url?<img src={v.image_url} alt={v.title} loading="lazy"/>:<span>Kein Vorschaubild</span>}<span><Play size={17}/> {durationLabel(v.duration)}</span></a><div><h3>{v.title}</h3><p>Veröffentlicht am {dateLabel(v.published_at)} · Länge {durationLabel(v.duration)}</p><dl className="yt-primary-kpis">{primary.map(k=><div key={k}><dt>{kpis[k]}</dt><dd>{metric(v,k)}</dd></div>)}</dl><details><summary>Interaktionen &amp; Zugriffsquellen</summary><dl className="yt-detail-kpis">{['likes','comments','shares'].map(k=><div key={k}><dt>{kpis[k]}</dt><dd>{metric(v,k)}</dd></div>)}</dl><SourceToggle id={v.id} month={month} year={year}/></details></div></article>)}</div>{list.length>5&&<button className="button" onClick={()=>setExpanded(!expanded)}>{expanded?'Weniger Videos anzeigen':`Alle ${list.length} Videos anzeigen`}</button>}
 </>)}
 <PromotedVideos demo={demo} playlists={latest.data?.playlists||q.data?.playlists}/>
 <section className="yt-knowledge" aria-labelledby="yt-knowledge-title"><div className="yt-knowledge-heading"><span>Von Zahlen zu Wirkung</span><h2 id="yt-knowledge-title">Kennzahlen verstehen.</h2><p>Was misst der Wert – und was bedeutet er für das Marketing?</p><label>Kennzahl auswählen<select value={explain} onChange={e=>setExplain(e.target.value)}>{Object.entries(kpis).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><div className="yt-knowledge-content" aria-live="polite"><span>Einordnung</span><h3>{kpis[explain]}</h3><p>{explanations[explain]}</p></div></section>
 <details className="yt-roadmap"><summary>Welche Kennzahlen könnten die Auswertung ergänzen?</summary><p>Thumbnail-Impressionen und Klickrate helfen, Titel und Vorschaubild zu optimieren. Die Zuschauerbindung im Einstieg zeigt, wo Interesse verloren geht. Diese Kennzahlen sind noch nicht angebunden; sie werden nicht geschätzt.</p></details>
 <RecommendationTeaser/><EditorialQuote portrait={asset('brand/portraits/steven-spielberg-v1.png')} text="My job is to put the audience inside the movie." author="Steven Spielberg" role="Regisseur und Produzent" source="https://www.dga.org/craft/dgaq/issues/0604-winter-2006/dga-interview-steven-spielberg" sourceLabel="Quelle: Directors Guild of America"/>
 </section>;
}
function SourceToggle({id,month,year}:{id:string;month:string;year:boolean}){const [open,setOpen]=useState(false);return <><button className="text-button" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Zugriffsquellen schliessen':'Zugriffsquellen laden'}</button>{open&&<Sources id={id} month={month} year={year}/>}</>;}

function PromotedVideos({demo,playlists}:{demo:boolean;playlists?:Library["playlists"]}) {
 const [year,setYear]=useState('all');
 const q=useQuery({queryKey:['youtube-promoted'],queryFn:()=>api<{videos:(Video&{promotion:{paid_views:number;other_views:number|null;paid_watch_minutes:number|null}})[];updated_at:string;warning?:string}>('/youtube/promoted'),enabled:!demo,staleTime:3600000});
 const [busy,setBusy]=useState(false),[error,setError]=useState(false);
 const providerIds=playlists?.find(p=>playlistName(p.title)==='Full Service Provider')?.video_ids;
 const videos=(q.data?.videos||[]).filter(v=>providerIds?.includes(v.id));
 const years=[...new Set(videos.map(v=>new Date(v.published_at).toLocaleDateString('sv-SE',{timeZone:'Europe/Zurich'}).slice(0,4)))].sort().reverse();
 const selected=videos.filter(v=>year==='all'||new Date(v.published_at).toLocaleDateString('sv-SE',{timeZone:'Europe/Zurich'}).startsWith(year));
 return <section className="yt-promoted"><div className="section-heading yt-section-title"><h2>Mit Video mehr erreichen.</h2><label>Veröffentlichungsjahr<select aria-label="Jahr der Full-Service-Provider-Videos" value={year} onChange={e=>setYear(e.target.value)}><option value="all">Alle Jahre</option>{years.map(y=><option key={y} value={y}>Ganzes Jahr {y}</option>)}</select></label></div><p>Videos der Playlist Full Service Provider mit nachgewiesenen Aufrufen über YouTube-Werbung. Unabhängig von der Auswahl oben, mit verfügbaren Werten seit Veröffentlichung. Weitere Quellen enthalten auch direkte und unbekannte Zugriffe – sie sind nicht pauschal organisch.</p><button className="text-button" disabled={demo||busy||q.isPending} onClick={async()=>{setBusy(true);setError(false);try{await api('/youtube/promoted?refresh=true');await q.refetch()}catch{setError(true)}finally{setBusy(false)}}}>{busy?'Wird aktualisiert…':'Videodaten aktualisieren'}</button>
 {demo?<p>Keine Live-Werbedaten in der Demo.</p>:q.isPending?<p role="status">Werbequellen aller Kanalvideos werden geprüft. Der erste Abruf kann etwas dauern…</p>:q.isError?<p role="alert">Werbequellen konnten nicht geladen werden. <button onClick={()=>q.refetch()}>Erneut versuchen</button></p>:<><p>Datenstand: {q.data?.updated_at?new Date(q.data.updated_at).toLocaleString('de-CH'):'—'}</p>{!playlists?<p role="status">Playlist-Zuordnung wird geladen…</p>:!providerIds?<p>Die Playlist Full Service Provider ist derzeit nicht verfügbar.</p>:!selected.length&&<p>Für diese Auswahl wurden keine Aufrufe über Werbung geliefert.</p>}<MetricHelp label="Kennzahlen der Werbeaufrufe erklärt" entries={[{"key": "Aufrufe über Werbung", "label": "Aufrufe über Werbung", "text": "Von YouTube der Zugriffsquelle Werbung zugeordnete Aufrufe seit Veröffentlichung. Wiederholte Aufrufe können enthalten sein; der Wert zählt keine eindeutigen Personen. Er zeigt bezahlte Nutzung, belegt aber nicht, wie viele Aufrufe ohne Werbung ausgeblieben wären."}, {"key": "Aufrufe weiterer Quellen", "label": "Aufrufe weiterer Quellen", "text": "Aufrufe seit Veröffentlichung aus allen anderen von YouTube gelieferten Zugriffsquellen, etwa Suche, Empfehlungen oder externen Websites. Direkte und unbekannte Zugriffe können enthalten sein; der Wert ist deshalb nicht pauschal organische Reichweite."}, {"key": "Wiedergabezeit Werbung", "label": "Wiedergabezeit Werbung", "text": "Die von YouTube geschätzte gesamte Betrachtungszeit der über Werbung zugeordneten Aufrufe seit Veröffentlichung, in Minuten. Sie zeigt das betrachtete Videovolumen, nicht die durchschnittliche Sehdauer. Für die Einordnung auch Werbeaufrufe und Videolänge berücksichtigen."}]}/><div className="yt-editorial-list">{selected.map(v=><article className="yt-editorial-video" key={v.id}><a className="yt-thumbnail" href={`https://www.youtube.com/watch?v=${v.id}`} target="_blank" rel="noreferrer">{v.image_url&&<img src={v.image_url} alt={v.title} loading="lazy"/>}<span><Play size={17}/>{durationLabel(v.duration)}</span></a><div><h3>{v.title}</h3><p>{dateLabel(v.published_at)} · Länge {durationLabel(v.duration)}</p><dl className="yt-primary-kpis"><div><dt>Aufrufe über Werbung</dt><dd>{number(v.promotion.paid_views)}</dd></div><div><dt>Aufrufe weiterer Quellen</dt><dd>{number(v.promotion.other_views)}</dd></div><div><dt>Wiedergabezeit Werbung</dt><dd>{number(v.promotion.paid_watch_minutes)} Min.</dd></div></dl></div></article>)}</div></>}{(error||q.data?.warning)&&<p role="alert">{q.data?.warning||'Aktualisierung fehlgeschlagen. Der letzte Stand bleibt sichtbar.'}</p>}<p>Werbekosten und Kampagnendetails folgen nach bestätigter Google-Ads-Anbindung. Die Werbeaufrufe sind in den Videowerten enthalten und werden nicht zusätzlich addiert.</p></section>;
}
