import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api, number, monthName } from '../api';
type Video={id:string;title:string;published_at:string;image_url:string|null;duration?:string;lifetime?:Record<string,number>;metrics:Record<string,number|null>|null};
type Library={videos:Video[];playlists:{id:string;title:string;video_ids:string[]}[];start:string;end:string;updated_at:string;warning?:string};
const labels:Record<string,string>={YT_OTHER_PAGE:'Weitere YouTube-Seiten',YT_SEARCH:'YouTube-Suche',RELATED_VIDEO:'Empfohlene Videos',EXT_URL:'Externe Websites',NO_LINK_OTHER:'Direkt oder unbekannt',SUBSCRIBER:'Startseite & Abos',ADVERTISING:'Werbung',PLAYLIST:'Playlists',YT_CHANNEL:'Kanalseiten',END_SCREEN:'Abspann',NOTIFICATION:'Benachrichtigungen',SHORTS:'Shorts-Feed'};
const kpis:Record<string,string>={views:'Aufrufe',estimatedMinutesWatched:'Wiedergabezeit (Min.)',averageViewDuration:'Ø Betrachtungsdauer (Sek.)',averageViewPercentage:'Ø angesehen (%)',likes:'Likes',comments:'Kommentare',shares:'Geteilt'};
const explanations:Record<string,string>={
views:'Aufrufe zeigt, wie oft YouTube das Video seit Veröffentlichung gezählt hat. Das ist keine Anzahl eindeutiger Personen: Wiederholte Aufrufe können enthalten sein. Nutze die Kennzahl für Reichweite und gemeinsam mit der Betrachtungsdauer für die Nutzung. Werbung kann enthalten sein; die Zugriffsquellen helfen bei der Einordnung.',
estimatedMinutesWatched:'Wiedergabezeit ist die von YouTube geschätzte gesamte Betrachtungszeit seit Veröffentlichung, angegeben in Minuten. Sie verbindet Aufrufmenge und Sehdauer. Viele Minuten können durch viele kurze oder wenige lange Aufrufe entstehen. Vergleiche deshalb auch Aufrufe, Videolänge und durchschnittliche Betrachtungsdauer. YouTube liefert gerundete Minuten; 0 Minuten muss nicht bedeuten, dass niemand kurz zugesehen hat.',
averageViewDuration:'Die durchschnittliche Betrachtungsdauer zeigt, wie viele Sekunden ein Video pro berücksichtigtem Aufruf angesehen wurde. YouTube berechnet diesen Durchschnitt. Setze ihn zur Videolänge ins Verhältnis: 30 Sekunden sind bei einem kurzen Testimonial anders zu bewerten als bei einem zehnminütigen Interview. Ohne Aufrufe ist kein sinnvoller Durchschnitt möglich; dann steht hier «—».',
averageViewPercentage:'Dieser Wert beschreibt, welcher Anteil der Videolänge durchschnittlich angesehen wurde. 50 % bedeutet ungefähr die halbe Videolänge pro berücksichtigtem Aufruf, nicht dass die Hälfte aller Zuschauer bis zum Ende blieb. Wiederholungen können Werte über 100 % erzeugen. Vergleiche möglichst ähnliche Formate und Längen; bei sehr wenigen Aufrufen schwankt der Wert stark.',
likes:'Likes zeigt den aktuellen Bestand positiver Bewertungen am Video laut YouTube. Sie zeigen aktive Zustimmung, aber nicht die Meinung aller Zuschauer. Vergleiche sie im Verhältnis zu Aufrufen und bei ähnlichen Inhalten. Die Zahl zeigt den aktuellen Like-Bestand am Video.',
comments:'Kommentare zeigt den aktuellen Kommentarbestand am Video laut YouTube. Sie zeigen Gesprächsaktivität, keine automatisch positive Resonanz und keine eindeutige Personenzahl. Für eine Bewertung solltest du zusätzlich den Inhalt der Kommentare ansehen. Die Zahl zeigt den aktuellen Kommentarbestand am Video.',
shares:'Geteilt zählt die von YouTube erfassten Teilungen seit Veröffentlichung, etwa über die Teilen-Funktion. Manuell kopierte Links oder Weiterleitungen ausserhalb der erfassten Funktionen sind nicht vollständig abgedeckt. Teilungen zeigen Weiterempfehlung, belegen aber weder zusätzliche Aufrufe noch Website-Conversions.'};
function durationLabel(value?:string){const m=value?.match(/^P(?:(\d+)D)?T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/);if(!m)return '—';const seconds=Number(m[1]||0)*86400+Number(m[2]||0)*3600+Number(m[3]||0)*60+Number(m[4]||0);return seconds>=3600?`${Math.floor(seconds/3600)}:${String(Math.floor(seconds/60)%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`:`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
function Sources({id,month}:{id:string;month:string}) {
 const q=useQuery({queryKey:['youtube-lifetime-traffic',id,month],queryFn:()=>api<{sources:{source:string;views:number;watch_minutes:number}[]}>(`/youtube/videos/${id}/traffic?month=${month}`),staleTime:3600000});
 return <div className="yt-sources">{q.isPending?<p role="status">Zugriffsquellen werden geladen…</p>:q.isError?<p role="alert">Zugriffsquellen konnten nicht geladen werden. <button onClick={()=>q.refetch()}>Erneut versuchen</button></p>:<><p>YouTube ordnet Aufrufe diesen Quellen zu. Externe Websites sind zusammengefasst; einzelne Personen werden nicht angezeigt.</p>{q.data?.sources.length?<dl>{q.data.sources.map(s=><div key={s.source}><dt>{labels[s.source]||s.source}</dt><dd>{number(s.views)} Aufrufe</dd></div>)}</dl>:<p>Für diesen Zeitraum liefert YouTube keine Zugriffsquellen.</p>}</>}</div>;
}
export function YouTubeVideos({demo}:{demo:boolean}) {
 const current=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Zurich',year:'numeric',month:'2-digit'}).format(new Date());
 const [month,setMonth]=useState(current),[playlist,setPlaylist]=useState(''),[video,setVideo]=useState(''),[explain,setExplain]=useState('views'),[opened,setOpened]=useState<string|null>(null);
 const q=useQuery({queryKey:['youtube-published-videos',month],queryFn:()=>api<Library>(`/youtube/videos?month=${month}`),enabled:!demo,staleTime:3600000});
 const [refreshing,setRefreshing]=useState(false),[refreshError,setRefreshError]=useState(false);
 const list=q.data?.videos.filter(v=>(!playlist||q.data?.playlists.find(p=>p.id===playlist)?.video_ids.includes(v.id))&&(!video||v.id===video))||[];
 return <section className="yt-library"><div className="section-heading"><div><h2>Deine Videos</h2><p>Videos nach Veröffentlichungsmonat. Alle Kennzahlen zeigen den aktuellen Gesamtstand seit Veröffentlichung.</p></div></div>
 <div className="yt-filters"><label>Veröffentlichungsmonat<select aria-label="Monat" value={month} onChange={e=>{setMonth(e.target.value);setVideo('');setOpened(null)}}>{Array.from({length:120},(_,i)=>{const d=new Date(current+"-01T12:00:00");d.setMonth(d.getMonth()-i);const m=String(d.getFullYear())+"-"+String(d.getMonth()+1).padStart(2,"0");return <option key={m} value={m}>{monthName(m)}</option>})}</select></label><label>Playlist<select aria-label="Playlist" value={playlist} onChange={e=>{setPlaylist(e.target.value);setVideo('')}}><option value="">Alle Playlists</option>{q.data?.playlists.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Video<select aria-label="Video" value={video} onChange={e=>setVideo(e.target.value)}><option value="">Alle Videos</option>{q.data?.videos.filter(v=>!playlist||q.data?.playlists.find(p=>p.id===playlist)?.video_ids.includes(v.id)).map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label><button className="button primary" style={{minHeight:44}} disabled={demo||refreshing||q.isPending} onClick={async()=>{setRefreshing(true);setRefreshError(false);try{await api(`/youtube/videos?month=${month}&refresh=true`);await q.refetch()}catch{setRefreshError(true)}finally{setRefreshing(false)}}}>{refreshing?'Wird aktualisiert…':'Videos aktualisieren'}</button></div>
 {demo?<p>Videodetails sind in der öffentlichen Demo nicht verfügbar.</p>:q.isPending?<p role="status">Videos, Playlists und Gesamtkennzahlen werden geladen…</p>:q.isError?<p role="alert">Videos konnten nicht geladen werden. <button onClick={()=>q.refetch()}>Erneut versuchen</button></p>:<>
 <p>{monthName(month)} · {list.length} Videos · Aktueller Gesamtstand, abgerufen am {q.data?.updated_at ? new Date(q.data.updated_at).toLocaleString('de-CH') : '—'}. Fehlende Werte erscheinen als «—». Aufrufe, Likes und Kommentare sind aktuelle Videobestände; die übrigen Werte stammen aus YouTube Analytics und können verzögert sein. Playlist-Auswahl filtert zugehörige Videos, unabhängig vom Wiedergabeort.</p>{(q.data?.warning||refreshError)&&<p role="alert">{q.data?.warning||'Aktualisierung fehlgeschlagen. Der letzte Stand bleibt sichtbar.'}</p>}
 <div className="yt-video-list">{list.map(v=><article key={v.id} className="yt-video"><div className="yt-video-main">{v.image_url?<img src={v.image_url} alt={`Vorschaubild: ${v.title}`} loading="lazy"/>:<div>Kein Vorschaubild</div>}<div><h3><a href={`https://www.youtube.com/watch?v=${v.id}`} target="_blank" rel="noreferrer">{v.title}</a></h3><p>Veröffentlicht am {new Date(v.published_at).toLocaleDateString('de-CH')} · Länge: {durationLabel(v.duration)}</p><dl className="yt-kpis">{Object.entries(kpis).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{number(v.metrics?.[key])}</dd></div>)}</dl><button className="text-button" aria-expanded={opened===v.id} onClick={()=>setOpened(opened===v.id?null:v.id)}>Zugriffsquellen {opened===v.id?'schliessen':'anzeigen'}</button></div></div>{opened===v.id&&<Sources id={v.id} month={month}/>}</article>)}</div>{!list.length&&<p>Keine Videos für diese Auswahl vorhanden.</p>}</>}
 <div className="yt-explainer"><h3>So liest du diese Zahlen</h3><label>KPI erklärt <select value={explain} onChange={e=>setExplain(e.target.value)}>{Object.entries(kpis).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><p>{explanations[explain]}</p></div></section>;
}
