CHANNELS = [
    {
        "id": "google_ads",
        "name": "Google Ads",
        "type": "Paid Search",
        "color": "#4285f4",
        "primary": "conversions",
        "fields": {
            "impressions": "Impressionen",
            "clicks": "Klicks",
            "conversions": "Conversions",
            "spend": "Werbekosten",
        },
    },
    {
        "id": "analytics",
        "name": "Google Analytics",
        "type": "Website",
        "color": "#e99b21",
        "primary": "sessions",
        "fields": {
            "sessions": "Sitzungen",
            "engaged_sessions": "Engagierte Sitzungen",
            "key_events": "Schlüsselereignisse",
        },
    },
    {
        "id": "linkedin",
        "name": "LinkedIn Ads",
        "type": "Paid Social",
        "color": "#0a66c2",
        "primary": "conversions",
        "fields": {
            "impressions": "Impressionen",
            "clicks": "Klicks",
            "conversions": "Conversions",
            "spend": "Werbekosten",
        },
    },
    {
        "id": "linkedin_organic",
        "name": "LinkedIn Organic",
        "type": "Social Media",
        "color": "#4791b8",
        "primary": "impressions",
        "fields": {
            "impressions": "Impressionen",
            "clicks": "Klicks",
            "likes": "Likes",
            "comments": "Kommentare",
            "shares": "Geteilte Beiträge",
            "followers_gained": "Neue Follower",
            "followers_organic": "Neue Follower (organisch)",
            "followers_paid": "Neue Follower (bezahlt)",
        },
    },
    {
        "id": "mailchimp",
        "name": "Mailchimp",
        "type": "E-Mail Marketing",
        "color": "#bb951e",
        "primary": "unique_clicks",
        "fields": {
            "emails_sent": "Versendete E-Mails",
            "unique_opens": "Öffnende je Kampagne",
            "unique_clicks": "Klickende je Kampagne",
        },
    },
    {
        "id": "youtube",
        "name": "YouTube",
        "type": "Video",
        "color": "#e3514f",
        "primary": "views",
        "fields": {
            "views": "Aufrufe",
            "watch_minutes": "Wiedergabezeit (Min.)",
            "subscribers_gained": "Neue Abonnenten",
        },
    },
    {
        "id": "events",
        "name": "Events",
        "type": "Word-Anmeldelisten",
        "color": "#7f74c0",
        "primary": "registrations",
        "fields": {"registrations": "Anmeldungen"},
    },
    {
        "id": "qr",
        "name": "QR Tracking",
        "type": "Offline → Online",
        "color": "#608575",
        "primary": "scans",
        "fields": {"scans": "Scans"},
    },
]
BY_ID = {c["id"]: c for c in CHANNELS}
DEFAULT_KPIS = [
    {
        "channel": "google_ads",
        "key": "conversions",
        "label": "Google Ads Conversions",
        "target": None,
    },
    {
        "channel": "analytics",
        "key": "sessions",
        "label": "Website-Sitzungen",
        "target": None,
    },
    {
        "channel": "mailchimp",
        "key": "unique_clicks",
        "label": "E-Mail-Klickende",
        "target": None,
    },
    {
        "channel": "events",
        "key": "registrations",
        "label": "Event-Anmeldungen",
        "target": None,
    },
]
