import type {Campaign,Data} from './components/AdsCampaigns';
export type AdsAdvice={id:string;campaign:string;title:string;observation:string;context:string;action:string;check:string;preparation:boolean};
const valid=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
const n=(v:number)=>v.toLocaleString('de-CH',{maximumFractionDigits:2});
const metric=(c:Campaign,key:string,label:string)=>valid(c.values[key])?`${n(c.values[key])} ${label}`:`${label}: nicht verfügbar`;
export function adsAdvice(data:Data):AdsAdvice[]{
 if(data.status!=='connected'||!data.last_success)return [];
 return data.campaigns.filter(c=>!c.example).map(c=>{
 const preparation=c.status==='DRAFT'||!!(c.start&&c.start>data.end);
 const base={id:c.id,campaign:c.name,preparation};
 if(preparation)return {...base,title:'Vor dem Start die Messung klären',observation:c.status==='DRAFT'?'Die Kampagne ist als Entwurf hinterlegt.':`Geplanter Start: ${c.start}.`,context:'Eine geplante Kampagne erhält noch keine Performance-Bewertung. Der Status allein bestätigt keine spätere Auslieferung.',action:c.objective==='LEAD_GENERATION'?'Vor Freigabe das zugeordnete Lead-Gen-Formular, die Bestätigungsseite und die Erfassung von Formularöffnungen und abgesendeten Formularen prüfen.':'Vor Freigabe Kampagnenziel, Motiv und Zielseite aufeinander abstimmen und die zum Ziel passende Messung prüfen.',check:'Nach dem tatsächlichen Start prüfen, ob Auslieferung und die vereinbarten Kennzahlen im Reporting erscheinen.'};
 if(!['impressions','clicks','landing_page_clicks','leads','lead_form_opens','conversions'].some(key=>valid(c.values[key])))return {...base,title:'Datenzeitraum vor einer Bewertung prüfen',observation:'Für diese Kampagne liegen im ausgewiesenen Zeitraum keine Ergebniskennzahlen vor.',context:'Eine bekannte Kampagne kann ausserhalb der letzten 365 Tage gelaufen sein. Fehlende Messwerte bedeuten nicht null Ergebnisse.',action:'Laufzeit und tatsächliche Auslieferung im LinkedIn Campaign Manager prüfen. Nur bei erwarteter Aktivität in diesem Zeitraum den Reporting-Zugriff und den Datenabruf prüfen.',check:'Erst nach bestätigten Messwerten eine Performance-Empfehlung ableiten.'};
 if(c.objective==='LEAD_GENERATION'){
 const leads=c.values.leads,opens=c.values.lead_form_opens;
 const rate=valid(leads)&&valid(opens)&&opens>0&&leads<=opens?` Abschlussrate: ${n(leads/opens*100)} %.`:'';
 return {...base,title:valid(leads)?'Formularinteresse in Anfragen übersetzen':'Lead-Erfassung zuerst bestätigen',observation:`${metric(c,'leads','abgesendete Formulare')}; ${metric(c,'lead_form_opens','Formularöffnungen')}.${rate}`,context:'Leads sind abgesendete LinkedIn-Formulare, keine bestätigten Verkaufschancen. Fehlende Werte sind keine null Leads. Kleine Mengen und Meldeverzögerungen begrenzen die Einordnung.',action:valid(leads)&&valid(opens)&&opens>0?'Nutzenversprechen der Anzeige und Formular gemeinsam prüfen. Bei erkennbarer Hürde eine einzelne Änderung an Erklärung oder Pflichtfeldern als Test festhalten.':'Prüfen, ob das richtige Lead-Gen-Formular mit der Kampagne verbunden ist und Öffnungen sowie Einsendungen im Reporting erfasst werden.',check:'Nach dem Test Formularöffnungen und Einsendungen über gleich lange Zeiträume prüfen; die Abschlussrate nur bei vollständigen Werten und vorhandenen Öffnungen verwenden.'};
 }
 if(c.objective==='BRAND_AWARENESS'||c.objective==='VIDEO_VIEW')return {...base,title:'Sichtbarkeit am Kommunikationsziel einordnen',observation:metric(c,'impressions','Impressionen')+'.',context:'Impressionen belegen Ausspielungen, keine eindeutige Reichweite oder gestiegene Markenbekanntheit. Wenige Klicks allein sind kein Misserfolg. Video-Aufmerksamkeit nur bei tatsächlich verfügbaren Videodaten beurteilen.',action:'Motiv und zentrale Botschaft dieser Kampagne prüfen. Für einen Folgetest genau eine Variante der Botschaft oder des Motives festlegen; Zielgruppe und Ziel möglichst konstant halten.',check:'Ausspielungen im gleichen Zeitfenster betrachten. Reichweite, Häufigkeit und Video-Aufmerksamkeit erst ergänzen, wenn verlässliche Messwerte vorliegen.'};
 if(c.objective==='WEBSITE_VISIT')return {...base,title:'Klickinteresse mit der Zielseite verbinden',observation:`${metric(c,'impressions','Impressionen')}; ${metric(c,'landing_page_clicks','Landingpage-Klicks')}${valid(c.ctr)?`; CTR ${n(c.ctr)} %`:''}.`,context:'Eine hohe CTR bei wenigen Impressionen ist kein belastbarer Gewinner. LinkedIn-Klicks sind nicht automatisch Website-Besuche; Landingpage-Klicks und tatsächliche Sitzungen bleiben getrennt.',action:'Versprechen der Anzeige mit dem Einstieg der Zielseite abgleichen. Bei einer konkreten Abweichung einen passenden Einstieg testen; die Zuordnung in Analytics über Kampagnenlinks prüfen.',check:'Landingpage-Klicks und – bei verifizierter Zuordnung – engagierte Sitzungen vor und nach dem Test betrachten. Nur innerhalb vergleichbarer Ziele und Zielgruppen einordnen.'};
 return {...base,title:'Ziel und Messung konkretisieren',observation:`Kampagnenziel: ${c.objective||'nicht angegeben'}. ${metric(c,'impressions','Impressionen')}.`,context:'Website-Zielaktionen sind nicht automatisch Leads. Ohne verifiziertes Ziel lassen sich weder Erfolg noch Optimierungsbedarf zuverlässig ableiten.',action:'Das konkrete Kampagnenziel und die dazugehörige Messgrösse bestätigen. Bei Website-Conversions prüfen, welches Ereignis tatsächlich gezählt wird.',check:'Erst mit bestätigter Definition und verfügbaren Werten einen konkreten Optimierungstest festlegen.'};
 }).sort((a,b)=>Number(b.preparation)-Number(a.preparation)||Number(a.title==='Datenzeitraum vor einer Bewertung prüfen')-Number(b.title==='Datenzeitraum vor einer Bewertung prüfen')||a.campaign.localeCompare(b.campaign,'de'));
}
