export type AnalyticsSources={ai:{providers:{label:string;value:number}[];evidence:{source:string;sessions:number;provider:string}[]};sources:{channel:string;sessions:number}[];start:string;end:string;updated_at:string;warning?:string;thresholded:boolean;data_loss:boolean};
export type AnalyticsPagesReport={pages:{path:string;title:string;kind?:string|null;current:Record<string,number|null>|null}[];start:string;end:string;updated_at:string;warning?:string;thresholded:boolean};
export type AnalyticsAdvice={id:string;title:string;observation:string;context:string;action:string;check:string};
const valid=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
const n=(v:number)=>v.toLocaleString('de-CH',{maximumFractionDigits:1});
export function analyticsAdvice(pages?:AnalyticsPagesReport,sources?:AnalyticsSources):AnalyticsAdvice[]{
 const result:AnalyticsAdvice[]=[];
 if(pages?.updated_at&&!pages.warning&&!pages.thresholded){
 const page=[...pages.pages].filter(p=>p.kind&&!/^\/(?:fr-ch\/)?services\/support(?:\/|$)/i.test(p.path)&&valid(p.current?.screenPageViews)&&p.current!.screenPageViews!>0).sort((a,b)=>b.current!.screenPageViews!-a.current!.screenPageViews!)[0];
 if(page){result.push({id:'content',title:'Ein gefragtes Thema weiterführen',observation:`«${page.title||page.path}»: ${n(page.current!.screenPageViews!)} Seitenaufrufe im Berichtsmonat. Höchste Aufrufzahl unter den erkannten Fachinhalten.`,context:'Aufrufe messen Nutzung, nicht automatisch Zufriedenheit oder Kaufabsicht. Bewerbung, Veröffentlichungsalter und Thema können die Nachfrage beeinflussen.',action:`Die Seite ${page.path} öffnen und prüfen, welche konkrete Anschlussfrage sie offenlässt. Einen passenden weiterführenden Inhalt auswählen, statt allein wegen vieler Aufrufe neue Inhalte zu produzieren.`,check:'Nach der Änderung Aufrufe und tatsächlich erfasste weiterführende Aktionen über vergleichbare Zeiträume betrachten.'});
 result.push({id:'next-step',title:'Den nächsten Schritt auf der Seite prüfen',observation:`Ausgangspunkt ist «${page.title||page.path}» mit ${n(page.current!.screenPageViews!)} Aufrufen im Berichtsmonat.`,context:'Aus Seitenaufrufen lässt sich nicht erkennen, ob Downloads oder Kontakte zustande kamen. Ohne bestätigte Ereignismessung wird kein Erfolg oder Ausstieg behauptet.',action:'Prüfen, ob ein fachlich passender Download, Kontakt oder weiterführender Link klar auffindbar ist. Vor einem Test die Messung genau dieser Aktion bestätigen.',check:'Nur das bestätigte Ereignis auswerten; Schlüsselereignisse nicht pauschal als Leads bezeichnen.'});}
 }
 if(sources?.updated_at&&!sources.warning&&!sources.thresholded&&!sources.data_loss){
 const top=[...sources.sources].filter(s=>valid(s.sessions)&&s.sessions>0).sort((a,b)=>b.sessions-a.sessions)[0];
 if(top)result.push({id:'sources',title:'Den Quellenmix mit Aktivitäten verbinden',observation:`${top.channel}: ${n(top.sessions)} Sitzungen, grösste gelieferte Kanalgruppe im Berichtsmonat.`,context:'Volumen allein bewertet keine Qualität. Organische, bezahlte und E-Mail-Zugriffe haben verschiedene Nutzungskontexte; veränderte Kampagnenaktivität beeinflusst den Mix.',action:'Die führende Quelle mit den laufenden Kampagnen, Mailings und Veröffentlichungen abgleichen. Erst danach für die zugehörigen Zielseiten einen konkreten Test bestimmen.',check:'Quellen und engagierte Sitzungen mit gleichem Zeitbezug prüfen; Besucher verschiedener Seiten nicht summieren.'});
 const providers=['ChatGPT','Claude','Microsoft Copilot','Perplexity'];
 const observed=sources.ai.providers.filter(p=>providers.includes(p.label)&&valid(p.value));
 result.push({id:'ai',title:'Erkennbare KI-Zugriffe einordnen',observation:providers.map(label=>{const p=observed.find(p=>p.label===label);return `${label}: ${p?n(p.value)+' Sitzungen':'keine zugeordnete Berichtszeile'}`}).join('; ')+'.',context:'Gemessen werden erkennbare Sitzungsquellen, keine Erwähnungen in KI-Antworten. Ohne übermittelte Quelle können Zugriffe nicht zuverlässig einer KI zugeordnet werden. Diese Sitzungen sind bereits im Quellenmix enthalten.',action:observed.some(p=>p.value>0)?'Die erfassten Quelldomains ansehen und bei relevanten Fachseiten die Herkunft prüfen. Erst bei wiederholten Signalen eine inhaltliche Testidee ableiten.':'Zunächst bei einem kontrollierten Besuch über einen tatsächlichen KI-Link prüfen, ob Quelle oder Kampagnenparameter in GA4 ankommen. Keine künstlichen KI-Zahlen ergänzen.',check:'Die vier Quellen im nächsten vergleichbaren Zeitraum erneut prüfen. Keine Berichtszeile bedeutet nicht nachgewiesene null Zugriffe.'});
 }
 return result;
}
