import type {Report} from './components/GoogleAds';
export type SearchEvidence={rows:{term:string;campaign?:string;clicks:number;impressions:number;conversions?:number}[];warning?:string;updated_at:string};
export type GoogleAdvice={id:string;title:string;observation:string;context:string;action:string;check:string};
const valid=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
const n=(v:number)=>v.toLocaleString('de-CH',{maximumFractionDigits:2});
export function googleAdsAdvice(report:Report,search?:SearchEvidence):GoogleAdvice[]{
 if(report.warning||!report.updated_at)return [];
 const result:GoogleAdvice[]=[];
 for(const c of report.campaigns){
 if(!valid(c.impressions)||c.impressions===0||!valid(c.clicks))continue;
 const observation=`«${c.name}» (${c.type}): ${n(c.impressions)} Impressionen, ${n(c.clicks)} Klicks${valid(c.ctr)?`, CTR ${n(c.ctr)} %`:''}${valid(c.conversions)?`, ${n(c.conversions)} erfasste Zielaktionen`:''}.`;
 const base={id:c.id,observation};
 if(c.type!=='SEARCH'){result.push({...base,title:'Kampagnenziel vor Klickbewertung klären',context:'Display, Video und Performance Max haben andere Ausspielungsbedingungen als Suchanzeigen. Das konkrete Kampagnenziel ist in diesen Berichtsdaten nicht hinterlegt.',action:'Für diese Kampagne das Ziel bestätigen. Bei Bekanntheit Sichtbarkeit und verfügbare Aufmerksamkeit einordnen; bei Zielaktionen zuerst deren Definition prüfen. Keine Bewertung anhand eines Search-CTR-Rankings.',check:'Erst nach Zielklärung einen einzelnen Test und die passende Kennzahl festlegen.'});continue;}
 if(c.clicks===0){result.push({...base,title:'Suchabsicht und Anzeigenversprechen prüfen',context:'Einblendungen ohne Klicks zeigen keine Ursache. Position, Suchabsicht und Auslieferungsdauer können mitwirken; eine einzelne Beobachtung reicht nicht für ein Qualitätsurteil.',action:'Die gemeldeten Suchanfragen dieser Kampagne mit Anzeigentext und Angebot abgleichen. Bei einer konkreten Abweichung genau eine Textvariante testen.',check:'CTR und absolute Klicks im gleichen Zeitraum bei vergleichbarer Auslieferung betrachten.'});continue;}
 if(!valid(c.conversions)||c.conversions===0){result.push({...base,title:'Messung vor Optimierung bestätigen',context:valid(c.conversions)?'Es sind null Zielaktionen erfasst. Das beweist weder fehlendes Interesse noch einen Trackingfehler; Meldeverzögerungen sind möglich.':'Zielaktionen sind nicht verfügbar. Fehlende Daten sind keine null Ergebnisse.',action:'Die erfassten Conversion-Ereignisse und ihre Funktion prüfen. Danach die Zielseite auf Übereinstimmung mit dem Anzeigenversprechen und einen klaren nächsten Schritt prüfen.',check:'Nach Bestätigung der Messung Klicks und Zielaktionen erneut auswerten; verzögerte Zuordnungen berücksichtigen.'});continue;}
 result.push({...base,title:'Klickinteresse mit dem Ergebnis verbinden',context:'Eine hohe CTR bei wenigen Impressionen ist kein belastbarer Gewinner. Zielaktionen können unterschiedliche Ereignisse sein, keine automatisch qualifizierten Leads. Das konkrete Ziel muss bestätigt werden.',action:'Die Conversion-Definition prüfen und Anzeige sowie Zielseite dieser Kampagne gemeinsam ansehen. Einen konkreten Verbesserungstest erst aus diesem Abgleich ableiten.',check:'Klicks und bestätigte Zielaktionen bei gleichem Kampagnenziel vergleichen; verschiedene Ziele nicht gegeneinander ranken.'});
 }
 if(search?.updated_at&&!search.warning){const term=[...search.rows].filter(r=>r.term&&!/\bsonio\b/i.test(r.term)&&valid(r.clicks)&&r.clicks>0&&r.conversions===0).sort((a,b)=>b.clicks-a.clicks)[0];if(term)result.unshift({id:'term:'+term.term+':'+term.campaign,title:'Suchanfrage auf fachliche Passung prüfen',observation:`«${term.term}»${term.campaign?` · ${term.campaign}`:''}: ${n(term.clicks)} Klicks, 0 erfasste Zielaktionen.`,context:'Nach Klicks ausgewählter Prüfhinweis, kein Beleg für Irrelevanz. Suchanfragenberichte können unvollständig sein; Zieldefinition und verzögerte Conversions bleiben zu beachten.',action:'Prüfen, ob hinter dieser Suchanfrage ein Bedarf steht, den Sonio mit der beworbenen Seite erfüllt. Nur bei bestätigter fachlicher Fehlpassung einen Ausschluss zur manuellen Freigabe vorschlagen.',check:'Die Entscheidung und ihre Begründung dokumentieren. Danach relevante Suchanfragen und Zielaktionen beobachten; es wird nichts automatisch ausgeschlossen.'});}
 return result;
}
