import type {Channel} from './types';
import type {Post} from './components/PerformanceExplorer';
export type OrganicAdvice={id:string;title:string;observation:string;context:string;action:string;check:string;url?:string};
const valid=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
const title=(p:Post)=>(p.title||p.text?.slice(0,120)||'Beitrag ohne Titel').normalize('NFKC').trim();
const n=(v:number)=>v.toLocaleString('de-CH',{maximumFractionDigits:1});
export function organicAdvice(channel:Channel|undefined,posts:Post[],complete:boolean):OrganicAdvice[]{
 const result:OrganicAdvice[]=[];
 const comparison=channel?.comparisons?.impressions;
 if(comparison?.status==='comparable'&&!comparison.stale&&valid(comparison.value)&&valid(comparison.previous))result.push({id:'context',title:'Sichtbarkeit im Veröffentlichungskontext',observation:`${n(comparison.value)} Impressionen gegenüber ${n(comparison.previous)} im vergleichbaren Vorzeitraum.`,context:`Vergleich: ${comparison.current_start} bis ${comparison.current_end}, zuvor ${comparison.previous_start} bis ${comparison.previous_end}. Impressionen messen Ausspielungen, keine eindeutigen Personen oder nachgewiesene Bekanntheit. Anzahl, Zeitpunkt und Themen der Beiträge beeinflussen das Ergebnis.`,action:'Die Veröffentlichungen beider Zeiträume dem Kampagnen-, Event- und Newsplan gegenüberstellen. Erst danach beurteilen, ob sich die Resonanz verändert hat – keine zusätzliche Posting-Frequenz allein aus dem Rückgang ableiten.',check:'Bei der nächsten Auswertung Postanzahl und Themenmix zusammen mit den Impressionen dokumentieren.'});
 if(!complete)return result;
 // Select by one explicit metric, never by an arbitrary combined resonance score.
 const ranked=posts.filter(p=>valid(p.metrics.clicks)&&p.metrics.clicks>0).sort((a,b)=>b.metrics.clicks-a.metrics.clicks||a.id.localeCompare(b.id));
 const lead=ranked[0];
 if(lead){const signals=[`${n(lead.metrics.clicks)} LinkedIn-Klicks`,valid(lead.metrics.comments)?`${n(lead.metrics.comments)} Kommentare`:null,valid(lead.metrics.shares)?`${n(lead.metrics.shares)} Reposts`:null].filter(Boolean).join(', ');result.push({id:'resonance',title:'Ein konkretes Thema weiterdenken',observation:`«${title(lead)}»: ${signals} seit Veröffentlichung. Höchste verfügbare Klickzahl in der Auswahl.`,context:'Ältere Beiträge konnten länger Ergebnisse sammeln. Klicks sind nicht automatisch Website-Besuche; Kommentare können auch Kritik enthalten. Ein einzelner Beitrag belegt noch kein Erfolgsmuster.',action:'Den Beitrag öffnen und die Reaktionen inhaltlich lesen. Falls eine passende Anschlussfrage erkennbar ist, diese in einem ergänzenden Beitrag testen.',check:'Den Folgetest bei vergleichbarem Veröffentlichungsalter anhand von Klicks, Kommentaren und Reposts beurteilen. Thema und Format festhalten.',url:lead.url});}
 const video=posts.filter(p=>p.kind==='video').sort((a,b)=>b.published_at.localeCompare(a.published_at))[0];
 if(video){const views=video.metrics.video_views,watch=video.metrics.watch_time_ms;const average=valid(views)&&views>0&&valid(watch)?watch/views/1000:null;result.push({id:'video',title:'Video am Kommunikationsziel beurteilen',observation:`«${title(video)}»: ${valid(views)?`${n(views)} qualifizierte Aufrufe`:'Aufrufe nicht verfügbar'}${average!==null?`, Ø ${n(average)} Sekunden Betrachtungsdauer`:''} seit Veröffentlichung.`,context:'Aufrufe belegen Nutzung, nicht automatisch gestiegene Markenbekanntheit. Die durchschnittliche Betrachtungsdauer zeigt weder den genauen Ausstiegspunkt noch dessen Ursache. Länge, Format und Veröffentlichungsalter gehören zur Einordnung.',action:'Für dieses Video festhalten, ob Bekanntheit, Verständnis oder eine konkrete Handlung im Vordergrund steht. Einen Einstiegstest erst nach Sichtung und Vergleich mit einem ähnlichen Format ableiten.',check:average===null?'Zuerst verfügbare Aufrufe und Wiedergabezeit prüfen. Ohne Betrachtungsdaten keine Aussage über Aufmerksamkeit treffen.':'Beim nächsten Video desselben Formats Aufrufe und Betrachtungsdauer bei vergleichbarer Länge und gleichem Alter prüfen; Klicks nur ergänzend bewerten.',url:video.url});}
 return result;
}
